<?php
/**
 * KRISHNA TOOLS — configuration.
 *
 * This is a SAMPLE. The real /config/config.php is written automatically by
 * the installer (/install/) — do NOT edit this sample by hand for production.
 * The installer generates config.php with your real credentials and then
 * creates /config/install.lock to disable the wizard.
 */

// Idempotent guard: safe even if this file is included more than once via
// different path strings (require_once compares literal paths).
if (defined('DB_HOST')) { return; }

// ── Database ──────────────────────────────────────────────
define('DB_HOST', 'localhost');
define('DB_NAME', 'akdwk_krishnatools');
define('DB_USER', 'akdwk_ktuser');
define('DB_PASS', 'your-db-password');
define('DB_PREFIX', 'kt_');
define('DB_CHARSET', 'utf8mb4');

// ── Site ──────────────────────────────────────────────────
define('SITE_NAME', 'કૃષ્ણા ટૂલ્સ');
define('SITE_URL', 'https://tools.akdwk.in');
define('DEFAULT_LANG', 'gu');          // gu | en
define('APP_TIMEZONE', 'Asia/Kolkata');
define('CURRENCY', 'INR');
// CURRENCY_SYMBOL is a predefined PHP constant, so we namespace ours.
define('KT_CURRENCY_SYMBOL', '₹');

// ── Security ──────────────────────────────────────────────
// A random secret is generated by the installer; used for CSRF + tokens.
define('APP_SECRET', 'change-me-random-secret');

// ── Optional integrations (blank = disabled) ──────────────
define('RAZORPAY_KEY_ID', '');
define('RAZORPAY_KEY_SECRET', '');

define('SMTP_HOST', '');
define('SMTP_PORT', '587');
define('SMTP_USER', '');
define('SMTP_PASS', '');
define('SMTP_FROM_NAME', 'Krishna Tools');

// WhatsApp (bulk.akdwk.in) — can also be overridden from the settings table.
define('WA_BASE_URL', 'https://bulk.akdwk.in/api.php');
define('WA_INBOUND_URL', 'https://bulk.akdwk.in/api/webhook_inbound.php');
define('WA_API_KEY', '');
define('WA_SESSION_ID', '');
define('WA_SENDER', '');

define('GA_ID', '');

// ── Paths ─────────────────────────────────────────────────
define('KT_ROOT', dirname(__DIR__));
define('KT_UPLOADS', KT_ROOT . '/uploads');
define('KT_LOGS', KT_ROOT . '/logs');
