<?php
/**
 * KRISHNA TOOLS — Master tool & category registry.
 *
 * Single source of truth used by:
 *   - the installer (seeds `categories` + `tools` tables)
 *   - the home page tool grid + live search
 *   - each tool page (name, icon, guide, FAQ, related tools, JSON-LD)
 *   - the admin tools manager
 *
 * Every tool is client-side-first (the browser does the conversion via CDN
 * libraries) unless a server binary is genuinely required, in which case the
 * tool degrades gracefully. See /includes/tool_wrapper.php for how these
 * definitions are rendered into a full, working tool page.
 */

/**
 * Category definitions. slug is used in clean URLs (/category/<slug>).
 * color is a Tailwind-friendly hex used for the category accent.
 */
function kt_categories(): array {
    return [
        ['slug' => 'image',    'name_en' => 'Image Tools',        'name_gu' => 'ઇમેજ ટૂલ્સ',            'icon' => 'image',        'color' => '#0E7490', 'sort_order' => 1],
        ['slug' => 'pdf',      'name_en' => 'PDF Tools',          'name_gu' => 'PDF ટૂલ્સ',             'icon' => 'file-text',    'color' => '#EA580C', 'sort_order' => 2],
        ['slug' => 'document', 'name_en' => 'Document & Text',    'name_gu' => 'ડોક્યુમેન્ટ અને ટેક્સ્ટ', 'icon' => 'file-code',    'color' => '#059669', 'sort_order' => 3],
        ['slug' => 'cctv',     'name_en' => 'CCTV & Security',    'name_gu' => 'CCTV અને સિક્યુરિટી',    'icon' => 'cctv',         'color' => '#1E3A8A', 'sort_order' => 4],
        ['slug' => 'computer', 'name_en' => 'Computer Shop',      'name_gu' => 'કમ્પ્યુટર શોપ',          'icon' => 'monitor',      'color' => '#7C3AED', 'sort_order' => 5],
        ['slug' => 'business', 'name_en' => 'Business & Shop',    'name_gu' => 'બિઝનેસ અને શોપ',         'icon' => 'briefcase',    'color' => '#B45309', 'sort_order' => 6],
        ['slug' => 'datetime', 'name_en' => 'Date, Time & Math',  'name_gu' => 'તારીખ, સમય અને ગણિત',    'icon' => 'calculator',   'color' => '#0891B2', 'sort_order' => 7],
        ['slug' => 'developer','name_en' => 'Developer & Misc',   'name_gu' => 'ડેવલપર અને અન્ય',        'icon' => 'code',         'color' => '#DB2777', 'sort_order' => 8],
        ['slug' => 'devtools', 'name_en' => 'Developer & API',    'name_gu' => 'ડેવલપર અને API',         'icon' => 'terminal',     'color' => '#334155', 'sort_order' => 9],
    ];
}

/**
 * All 120 tools. Fields:
 *   slug, cat (category slug), name_gu, name_en, icon (lucide),
 *   desc_gu, desc_en, premium (0/1), engine (the JS engine key in app.js
 *   that powers this tool; 'custom' means the tool file supplies its own JS),
 *   guide (4 Gujarati steps), faq ([[q,a],...] 3 items).
 *
 * `engine` lets ~all tools share one renderer while still being fully
 * functional. Calculator-type tools use lightweight formula engines; file
 * tools use CDN libraries loaded on demand.
 */
function kt_tools(): array {
    $g = function(...$s){ return $s; }; // guide helper (variadic -> array)
    return [
    // ───────────────────────── A) IMAGE (22) ─────────────────────────
    ['slug'=>'jpg-to-png','cat'=>'image','name_gu'=>'JPG થી PNG','name_en'=>'JPG to PNG','icon'=>'image','premium'=>0,'engine'=>'img-convert','opt'=>['to'=>'png'],
      'desc_gu'=>'JPG ઇમેજને પારદર્શક PNG ફોર્મેટમાં કન્વર્ટ કરો.','desc_en'=>'Convert JPG images to PNG format in your browser.',
      'guide'=>$g('JPG ફાઇલ પસંદ કરો','કન્વર્ટ બટન દબાવો','પરિણામ જુઓ','PNG ડાઉનલોડ કરો'),
      'faq'=>[['શું ડેટા સર્વર પર જાય છે?','ના, બધું તમારા બ્રાઉઝરમાં જ થાય છે.'],['ગુણવત્તા જળવાય છે?','હા, PNG lossless ફોર્મેટ છે.'],['કેટલી ફાઇલ?','ફ્રી માં દરરોજ 3 વખત.']]],
    ['slug'=>'png-to-jpg','cat'=>'image','name_gu'=>'PNG થી JPG','name_en'=>'PNG to JPG','icon'=>'image','premium'=>0,'engine'=>'img-convert','opt'=>['to'=>'jpeg'],
      'desc_gu'=>'PNG ઇમેજને નાની JPG ફાઇલમાં કન્વર્ટ કરો.','desc_en'=>'Convert PNG images to compact JPG.',
      'guide'=>$g('PNG ફાઇલ પસંદ કરો','ક્વોલિટી સેટ કરો','કન્વર્ટ કરો','JPG ડાઉનલોડ કરો'),
      'faq'=>[['પારદર્શકતા રહેશે?','ના, JPG સફેદ બેકગ્રાઉન્ડ ઉમેરે છે.'],['સાઇઝ ઘટે છે?','હા, JPG સામાન્ય રીતે નાની હોય છે.'],['સુરક્ષિત છે?','હા, ડેટા બ્રાઉઝરમાં જ રહે છે.']]],
    ['slug'=>'webp-to-jpg','cat'=>'image','name_gu'=>'WEBP થી JPG','name_en'=>'WEBP to JPG','icon'=>'image','premium'=>0,'engine'=>'img-convert','opt'=>['to'=>'jpeg'],
      'desc_gu'=>'WEBP ઇમેજને JPG માં કન્વર્ટ કરો.','desc_en'=>'Convert WEBP images to JPG.',
      'guide'=>$g('WEBP પસંદ કરો','કન્વર્ટ કરો','પ્રિવ્યૂ જુઓ','ડાઉનલોડ કરો'),
      'faq'=>[['WEBP શું છે?','Google નું આધુનિક ઇમેજ ફોર્મેટ.'],['ક્વોલિટી?','ઉચ્ચ ગુણવત્તા જળવાય છે.'],['ફ્રી?','હા, દરરોજ 3 વખત ફ્રી.']]],
    ['slug'=>'jpg-to-webp','cat'=>'image','name_gu'=>'JPG થી WEBP','name_en'=>'JPG to WEBP','icon'=>'image','premium'=>0,'engine'=>'img-convert','opt'=>['to'=>'webp'],
      'desc_gu'=>'JPG ને નાના WEBP ફોર્મેટમાં કન્વર્ટ કરો.','desc_en'=>'Convert JPG to modern WEBP format.',
      'guide'=>$g('JPG પસંદ કરો','ક્વોલિટી સેટ કરો','કન્વર્ટ કરો','WEBP ડાઉનલોડ'),
      'faq'=>[['WEBP કેમ?','30% સુધી નાની ફાઇલ.'],['બ્રાઉઝર સપોર્ટ?','બધા આધુનિક બ્રાઉઝર.'],['સુરક્ષિત?','હા.']]],
    ['slug'=>'heic-to-jpg','cat'=>'image','name_gu'=>'HEIC થી JPG','name_en'=>'HEIC to JPG','icon'=>'image','premium'=>0,'engine'=>'heic-convert',
      'desc_gu'=>'iPhone ના HEIC ફોટાને JPG માં કન્વર્ટ કરો.','desc_en'=>'Convert iPhone HEIC photos to JPG.',
      'guide'=>$g('HEIC ફાઇલ પસંદ કરો','પ્રોસેસ થવા દો','પ્રિવ્યૂ જુઓ','JPG ડાઉનલોડ'),
      'faq'=>[['HEIC શું છે?','iPhone નું ફોટો ફોર્મેટ.'],['કેમ કન્વર્ટ કરવું?','Windows માં ખૂલતું નથી.'],['ફ્રી?','હા.']]],
    ['slug'=>'image-to-pdf','cat'=>'image','name_gu'=>'ઇમેજ થી PDF','name_en'=>'Image to PDF','icon'=>'file-image','premium'=>0,'engine'=>'img-to-pdf',
      'desc_gu'=>'એક કે અનેક ફોટાને એક PDF માં ફેરવો.','desc_en'=>'Combine images into a single PDF.',
      'guide'=>$g('ફોટા પસંદ કરો','ક્રમ ગોઠવો','PDF બનાવો','ડાઉનલોડ કરો'),
      'faq'=>[['કેટલા ફોટા?','ફ્રી માં 5 સુધી.'],['ક્રમ બદલી શકાય?','હા, ડ્રેગ કરીને.'],['A4 સાઇઝ?','હા, ઓટો ફિટ.']]],
    ['slug'=>'pdf-to-jpg','cat'=>'image','name_gu'=>'PDF થી JPG','name_en'=>'PDF to JPG','icon'=>'file-image','premium'=>0,'engine'=>'pdf-to-img',
      'desc_gu'=>'PDF ના દરેક પાનાને JPG ઇમેજમાં ફેરવો.','desc_en'=>'Convert PDF pages to JPG images.',
      'guide'=>$g('PDF અપલોડ કરો','પાના પસંદ કરો','કન્વર્ટ કરો','ઇમેજ ડાઉનલોડ'),
      'faq'=>[['બધા પાના?','હા, દરેક પાનું અલગ ઇમેજ.'],['ક્વોલિટી?','ઉચ્ચ DPI.'],['ZIP?','પ્રીમિયમમાં.']]],
    ['slug'=>'image-compressor','cat'=>'image','name_gu'=>'ઇમેજ કોમ્પ્રેસર','name_en'=>'Image Compressor','icon'=>'minimize-2','premium'=>0,'engine'=>'img-compress',
      'desc_gu'=>'ટાર્ગેટ KB સુધી ઇમેજ કોમ્પ્રેસ કરો.','desc_en'=>'Compress images to a target KB size.',
      'guide'=>$g('ઇમેજ પસંદ કરો','ટાર્ગેટ KB આપો','કોમ્પ્રેસ કરો','ડાઉનલોડ કરો'),
      'faq'=>[['ક્વોલિટી ઘટે?','થોડી, પણ સાઇઝ ઘણી ઘટે.'],['ટાર્ગેટ સાઇઝ?','હા, KB માં.'],['ફોર્મ માટે?','હા, પરફેક્ટ.']]],
    ['slug'=>'image-resizer','cat'=>'image','name_gu'=>'ઇમેજ રિસાઇઝર','name_en'=>'Image Resizer','icon'=>'move','premium'=>0,'engine'=>'img-resize',
      'desc_gu'=>'પિક્સેલ, ટકા કે પ્રીસેટ પ્રમાણે ઇમેજ રિસાઇઝ કરો.','desc_en'=>'Resize images by px, %, or preset.',
      'guide'=>$g('ઇમેજ પસંદ કરો','સાઇઝ આપો','રિસાઇઝ કરો','ડાઉનલોડ કરો'),
      'faq'=>[['રેશિયો જળવાય?','હા, લોક વિકલ્પ છે.'],['પ્રીસેટ?','સોશિયલ મીડિયા સાઇઝ.'],['ફ્રી?','હા.']]],
    ['slug'=>'image-cropper','cat'=>'image','name_gu'=>'ઇમેજ ક્રોપર','name_en'=>'Image Cropper','icon'=>'crop','premium'=>0,'engine'=>'img-crop',
      'desc_gu'=>'ઇમેજને ચોક્કસ ભાગમાં ક્રોપ કરો.','desc_en'=>'Crop images with aspect ratio presets.',
      'guide'=>$g('ઇમેજ પસંદ કરો','ક્રોપ એરિયા ખેંચો','રેશિયો પસંદ કરો','ડાઉનલોડ કરો'),
      'faq'=>[['રેશિયો?','1:1, 16:9 વગેરે.'],['રોટેટ?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'rotate-flip','cat'=>'image','name_gu'=>'રોટેટ / ફ્લિપ','name_en'=>'Rotate & Flip','icon'=>'rotate-cw','premium'=>0,'engine'=>'img-rotate',
      'desc_gu'=>'ઇમેજને ફેરવો કે મિરર કરો.','desc_en'=>'Rotate or flip images.',
      'guide'=>$g('ઇમેજ પસંદ કરો','રોટેટ/ફ્લિપ કરો','પ્રિવ્યૂ જુઓ','ડાઉનલોડ કરો'),
      'faq'=>[['90 ડિગ્રી?','હા.'],['મિરર?','હા, હોરિઝોન્ટલ/વર્ટિકલ.'],['ફ્રી?','હા.']]],
    ['slug'=>'bulk-image-converter','cat'=>'image','name_gu'=>'બલ્ક ઇમેજ કન્વર્ટર','name_en'=>'Bulk Image Converter','icon'=>'layers','premium'=>1,'engine'=>'img-bulk',
      'desc_gu'=>'એકસાથે ઘણી ઇમેજ કન્વર્ટ કરી ZIP ડાઉનલોડ કરો.','desc_en'=>'Convert many images at once, download as ZIP.',
      'guide'=>$g('ઘણી ઇમેજ પસંદ કરો','ફોર્મેટ પસંદ કરો','કન્વર્ટ કરો','ZIP ડાઉનલોડ'),
      'faq'=>[['કેટલી ઇમેજ?','પ્રીમિયમમાં અમર્યાદિત.'],['ZIP?','હા.'],['સ્પીડ?','બ્રાઉઝર આધારિત.']]],
    ['slug'=>'passport-photo','cat'=>'image','name_gu'=>'પાસપોર્ટ ફોટો','name_en'=>'Passport Photo Maker','icon'=>'user-square','premium'=>0,'engine'=>'passport-photo',
      'desc_gu'=>'35×45mm પાસપોર્ટ ફોટો અને 4×6 શીટ બનાવો.','desc_en'=>'Make 35×45mm passport photos + 4×6 sheet.',
      'guide'=>$g('ફોટો અપલોડ કરો','પ્રીસેટ પસંદ કરો (India/US/UK)','ક્રોપ કરો','શીટ ડાઉનલોડ'),
      'faq'=>[['સાઇઝ?','35×45mm ભારત.'],['6 ફોટા?','હા, 4×6 શીટ.'],['પ્રિન્ટ?','હા.']]],
    ['slug'=>'signature-cleaner','cat'=>'image','name_gu'=>'સિગ્નેચર ક્લીનર','name_en'=>'Signature Cleaner','icon'=>'pen-tool','premium'=>0,'engine'=>'signature-clean',
      'desc_gu'=>'સહીનું સફેદ બેકગ્રાઉન્ડ દૂર કરી 20KB આઉટપુટ.','desc_en'=>'Remove white background from signatures, 20KB output.',
      'guide'=>$g('સહીનો ફોટો અપલોડ','થ્રેશોલ્ડ સેટ કરો','ક્લીન કરો','ડાઉનલોડ કરો'),
      'faq'=>[['બેકગ્રાઉન્ડ દૂર?','હા, સફેદ પારદર્શક બને.'],['ફોર્મ માટે?','હા.'],['સાઇઝ?','~20KB.']]],
    ['slug'=>'photo-kb-resizer','cat'=>'image','name_gu'=>'ફોટો 20/50/100 KB','name_en'=>'Photo to 20/50/100 KB','icon'=>'file-down','premium'=>0,'engine'=>'img-compress','opt'=>['presetKb'=>[20,50,100,200]],
      'desc_gu'=>'પરીક્ષા ફોર્મ માટે ફોટોને ચોક્કસ KB માં કરો.','desc_en'=>'Resize photos to exact KB for exam forms.',
      'guide'=>$g('ફોટો પસંદ કરો','KB પ્રીસેટ પસંદ','પ્રોસેસ કરો','ડાઉનલોડ કરો'),
      'faq'=>[['પરીક્ષા ફોર્મ માટે?','હા, ખાસ બનાવ્યું.'],['ચોક્કસ KB?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'watermark-adder','cat'=>'image','name_gu'=>'વોટરમાર્ક એડર','name_en'=>'Watermark Adder','icon'=>'stamp','premium'=>0,'engine'=>'img-watermark',
      'desc_gu'=>'ઇમેજ પર ટેક્સ્ટ કે લોગો વોટરમાર્ક ઉમેરો.','desc_en'=>'Add text or logo watermark to images.',
      'guide'=>$g('ઇમેજ પસંદ કરો','ટેક્સ્ટ/લોગો આપો','પોઝિશન સેટ કરો','ડાઉનલોડ કરો'),
      'faq'=>[['ઓપેસિટી?','હા, એડજસ્ટેબલ.'],['લોગો?','હા.'],['પોઝિશન?','9 વિકલ્પ.']]],
    ['slug'=>'image-to-base64','cat'=>'image','name_gu'=>'ઇમેજ ↔ Base64','name_en'=>'Image ↔ Base64','icon'=>'binary','premium'=>0,'engine'=>'img-base64',
      'desc_gu'=>'ઇમેજને Base64 કોડમાં અને પાછું કન્વર્ટ કરો.','desc_en'=>'Convert images to Base64 and back.',
      'guide'=>$g('ઇમેજ પસંદ કરો','એન્કોડ કરો','કોડ કોપી કરો','વાપરો'),
      'faq'=>[['Base64 શું છે?','ટેક્સ્ટ સ્વરૂપે ઇમેજ.'],['ડેવલપર માટે?','હા.'],['ડીકોડ?','હા.']]],
    ['slug'=>'favicon-generator','cat'=>'image','name_gu'=>'ફેવિકોન જનરેટર','name_en'=>'Favicon Generator','icon'=>'app-window','premium'=>0,'engine'=>'favicon-gen',
      'desc_gu'=>'બધા સાઇઝના ફેવિકોન બનાવી ZIP ડાઉનલોડ કરો.','desc_en'=>'Generate all-size favicons, ZIP download.',
      'guide'=>$g('ઇમેજ અપલોડ કરો','જનરેટ કરો','સાઇઝ જુઓ','ZIP ડાઉનલોડ'),
      'faq'=>[['કયા સાઇઝ?','16 થી 512px.'],['ICO?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'color-picker','cat'=>'image','name_gu'=>'કલર પિકર','name_en'=>'Color Picker from Image','icon'=>'pipette','premium'=>0,'engine'=>'color-picker',
      'desc_gu'=>'ઇમેજમાંથી કલર કોડ (HEX/RGB) મેળવો.','desc_en'=>'Pick colors (HEX/RGB) from an image.',
      'guide'=>$g('ઇમેજ અપલોડ કરો','પિક્સેલ પર ક્લિક કરો','કલર કોડ કોપી','વાપરો'),
      'faq'=>[['HEX/RGB?','બંને.'],['પેલેટ?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'exif-viewer','cat'=>'image','name_gu'=>'EXIF વ્યૂઅર/રિમૂવર','name_en'=>'EXIF Viewer & Remover','icon'=>'info','premium'=>0,'engine'=>'exif-tool',
      'desc_gu'=>'ફોટોની EXIF માહિતી જુઓ અને દૂર કરો.','desc_en'=>'View and remove EXIF metadata.',
      'guide'=>$g('ફોટો અપલોડ કરો','મેટાડેટા જુઓ','દૂર કરો','ડાઉનલોડ કરો'),
      'faq'=>[['EXIF શું?','કેમેરા/લોકેશન ડેટા.'],['પ્રાઇવસી?','દૂર કરીને શેર કરો.'],['ફ્રી?','હા.']]],
    ['slug'=>'meme-generator','cat'=>'image','name_gu'=>'મીમ જનરેટર','name_en'=>'Meme Generator','icon'=>'smile','premium'=>0,'engine'=>'meme-gen',
      'desc_gu'=>'ઉપર-નીચે ટેક્સ્ટ સાથે મીમ બનાવો.','desc_en'=>'Create memes with top/bottom text.',
      'guide'=>$g('ઇમેજ પસંદ કરો','ટેક્સ્ટ લખો','સ્ટાઇલ કરો','ડાઉનલોડ કરો'),
      'faq'=>[['ટેક્સ્ટ?','ઉપર અને નીચે.'],['ફોન્ટ?','ક્લાસિક મીમ ફોન્ટ.'],['ફ્રી?','હા.']]],
    ['slug'=>'dpi-changer','cat'=>'image','name_gu'=>'DPI ચેન્જર','name_en'=>'Image DPI Changer','icon'=>'printer','premium'=>0,'engine'=>'dpi-changer',
      'desc_gu'=>'પ્રિન્ટ માટે 72 થી 300 DPI બદલો.','desc_en'=>'Change DPI (72→300) for printing.',
      'guide'=>$g('ઇમેજ અપલોડ કરો','DPI આપો','પ્રોસેસ કરો','ડાઉનલોડ કરો'),
      'faq'=>[['DPI શું?','પ્રિન્ટ ગુણવત્તા.'],['300 DPI?','પ્રિન્ટ માટે.'],['ફ્રી?','હા.']]],

    // ───────────────────────── B) PDF (20) ─────────────────────────
    ['slug'=>'pdf-merge','cat'=>'pdf','name_gu'=>'PDF મર્જ','name_en'=>'Merge PDF','icon'=>'combine','premium'=>0,'engine'=>'pdf-merge',
      'desc_gu'=>'ઘણી PDF ને એક ફાઇલમાં જોડો.','desc_en'=>'Merge multiple PDFs into one.',
      'guide'=>$g('PDF ફાઇલો પસંદ કરો','ક્રમ ગોઠવો','મર્જ કરો','ડાઉનલોડ કરો'),
      'faq'=>[['કેટલી ફાઇલ?','ફ્રી માં 5.'],['ક્રમ?','ડ્રેગથી બદલો.'],['સુરક્ષિત?','હા, બ્રાઉઝરમાં.']]],
    ['slug'=>'pdf-split','cat'=>'pdf','name_gu'=>'PDF સ્પ્લિટ','name_en'=>'Split PDF','icon'=>'scissors','premium'=>0,'engine'=>'pdf-split',
      'desc_gu'=>'PDF ને પાના પ્રમાણે અલગ કરો.','desc_en'=>'Split a PDF into separate pages.',
      'guide'=>$g('PDF અપલોડ કરો','પાના રેન્જ આપો','સ્પ્લિટ કરો','ડાઉનલોડ કરો'),
      'faq'=>[['રેન્જ?','હા, 1-3 વગેરે.'],['દરેક પાનું?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'pdf-compress','cat'=>'pdf','name_gu'=>'PDF કોમ્પ્રેસ','name_en'=>'Compress PDF','icon'=>'minimize-2','premium'=>0,'engine'=>'pdf-compress',
      'desc_gu'=>'PDF ફાઇલ સાઇઝ ઘટાડો.','desc_en'=>'Reduce PDF file size.',
      'guide'=>$g('PDF અપલોડ કરો','લેવલ પસંદ કરો','કોમ્પ્રેસ કરો','ડાઉનલોડ કરો'),
      'faq'=>[['કેટલું ઘટે?','30-70%.'],['ક્વોલિટી?','સંતુલિત.'],['સર્વર?','Ghostscript ઉપલબ્ધ હોય તો.']]],
    ['slug'=>'pdf-to-word','cat'=>'pdf','name_gu'=>'PDF થી Word','name_en'=>'PDF to Word','icon'=>'file-type','premium'=>1,'engine'=>'pdf-to-word',
      'desc_gu'=>'PDF ને એડિટ કરી શકાય તેવા Word માં.','desc_en'=>'Convert PDF to editable Word.',
      'guide'=>$g('PDF અપલોડ કરો','કન્વર્ટ કરો','ટેક્સ્ટ ચેક કરો','DOCX ડાઉનલોડ'),
      'faq'=>[['લેઆઉટ?','ટેક્સ્ટ મુખ્ય રીતે.'],['સ્કેન PDF?','OCR જરૂરી.'],['ફ્રી?','પ્રીમિયમ.']]],
    ['slug'=>'word-to-pdf','cat'=>'pdf','name_gu'=>'Word થી PDF','name_en'=>'Word to PDF','icon'=>'file-type','premium'=>0,'engine'=>'server-convert','opt'=>['from'=>'docx','to'=>'pdf'],
      'desc_gu'=>'Word ડોક્યુમેન્ટને PDF માં કન્વર્ટ કરો.','desc_en'=>'Convert Word documents to PDF.',
      'guide'=>$g('DOCX અપલોડ કરો','કન્વર્ટ કરો','પ્રિવ્યૂ','PDF ડાઉનલોડ'),
      'faq'=>[['ફોર્મેટિંગ?','જળવાય છે.'],['સર્વર?','LibreOffice હોય તો.'],['ફ્રી?','હા.']]],
    ['slug'=>'pdf-to-excel','cat'=>'pdf','name_gu'=>'PDF થી Excel','name_en'=>'PDF to Excel','icon'=>'table','premium'=>1,'engine'=>'pdf-to-excel',
      'desc_gu'=>'PDF ના ટેબલને Excel માં કાઢો.','desc_en'=>'Extract PDF tables to Excel.',
      'guide'=>$g('PDF અપલોડ કરો','ટેબલ પસંદ કરો','કન્વર્ટ કરો','XLSX ડાઉનલોડ'),
      'faq'=>[['ટેબલ?','હા, ડિટેક્ટ થાય.'],['ચોકસાઈ?','સાદા ટેબલ સારા.'],['ફ્રી?','પ્રીમિયમ.']]],
    ['slug'=>'excel-to-pdf','cat'=>'pdf','name_gu'=>'Excel થી PDF','name_en'=>'Excel to PDF','icon'=>'table','premium'=>0,'engine'=>'sheet-to-pdf',
      'desc_gu'=>'Excel શીટને PDF માં કન્વર્ટ કરો.','desc_en'=>'Convert Excel sheets to PDF.',
      'guide'=>$g('XLSX અપલોડ કરો','શીટ પસંદ કરો','કન્વર્ટ કરો','PDF ડાઉનલોડ'),
      'faq'=>[['બધી શીટ?','હા.'],['ફોર્મેટ?','જળવાય.'],['ફ્રી?','હા.']]],
    ['slug'=>'pdf-to-ppt','cat'=>'pdf','name_gu'=>'PDF થી PPT','name_en'=>'PDF to PPT','icon'=>'presentation','premium'=>1,'engine'=>'pdf-to-ppt',
      'desc_gu'=>'PDF ને પ્રેઝન્ટેશનમાં કન્વર્ટ કરો.','desc_en'=>'Convert PDF to presentation.',
      'guide'=>$g('PDF અપલોડ','કન્વર્ટ','પ્રિવ્યૂ','PPTX ડાઉનલોડ'),
      'faq'=>[['દરેક પાનું?','એક સ્લાઇડ.'],['એડિટ?','હા.'],['ફ્રી?','પ્રીમિયમ.']]],
    ['slug'=>'ppt-to-pdf','cat'=>'pdf','name_gu'=>'PPT થી PDF','name_en'=>'PPT to PDF','icon'=>'presentation','premium'=>0,'engine'=>'server-convert','opt'=>['from'=>'pptx','to'=>'pdf'],
      'desc_gu'=>'પ્રેઝન્ટેશનને PDF માં કન્વર્ટ કરો.','desc_en'=>'Convert presentations to PDF.',
      'guide'=>$g('PPTX અપલોડ','કન્વર્ટ','પ્રિવ્યૂ','PDF ડાઉનલોડ'),
      'faq'=>[['સ્લાઇડ?','દરેક એક પાનું.'],['સર્વર?','LibreOffice.'],['ફ્રી?','હા.']]],
    ['slug'=>'pdf-to-text','cat'=>'pdf','name_gu'=>'PDF થી ટેક્સ્ટ','name_en'=>'PDF to Text','icon'=>'file-text','premium'=>0,'engine'=>'pdf-to-text',
      'desc_gu'=>'PDF માંથી ટેક્સ્ટ કાઢો.','desc_en'=>'Extract text from PDF.',
      'guide'=>$g('PDF અપલોડ','એક્સ્ટ્રેક્ટ','ટેક્સ્ટ કોપી','ડાઉનલોડ'),
      'faq'=>[['સ્કેન?','OCR જરૂરી.'],['બધા પાના?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'pdf-rotate','cat'=>'pdf','name_gu'=>'PDF રોટેટ','name_en'=>'Rotate PDF','icon'=>'rotate-cw','premium'=>0,'engine'=>'pdf-rotate',
      'desc_gu'=>'PDF પાના ફેરવો.','desc_en'=>'Rotate PDF pages.',
      'guide'=>$g('PDF અપલોડ','પાના પસંદ','રોટેટ','ડાઉનલોડ'),
      'faq'=>[['90°?','હા.'],['બધા પાના?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'pdf-delete-pages','cat'=>'pdf','name_gu'=>'પાના ડિલીટ','name_en'=>'Delete Pages','icon'=>'trash-2','premium'=>0,'engine'=>'pdf-delete',
      'desc_gu'=>'PDF માંથી પાના દૂર કરો.','desc_en'=>'Delete pages from PDF.',
      'guide'=>$g('PDF અપલોડ','પાના પસંદ','ડિલીટ','ડાઉનલોડ'),
      'faq'=>[['રેન્જ?','હા.'],['સુરક્ષિત?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'pdf-reorder','cat'=>'pdf','name_gu'=>'પાના ફરી ગોઠવો','name_en'=>'Reorder Pages','icon'=>'arrow-up-down','premium'=>0,'engine'=>'pdf-reorder',
      'desc_gu'=>'PDF પાનાનો ક્રમ બદલો.','desc_en'=>'Reorder PDF pages.',
      'guide'=>$g('PDF અપલોડ','પાના ડ્રેગ કરો','ગોઠવો','ડાઉનલોડ'),
      'faq'=>[['ડ્રેગ?','હા.'],['પ્રિવ્યૂ?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'pdf-extract-pages','cat'=>'pdf','name_gu'=>'પાના કાઢો','name_en'=>'Extract Pages','icon'=>'file-output','premium'=>0,'engine'=>'pdf-extract',
      'desc_gu'=>'ચોક્કસ પાના અલગ PDF માં કાઢો.','desc_en'=>'Extract specific pages to a new PDF.',
      'guide'=>$g('PDF અપલોડ','પાના પસંદ','એક્સ્ટ્રેક્ટ','ડાઉનલોડ'),
      'faq'=>[['રેન્જ?','હા.'],['નવી PDF?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'pdf-protect','cat'=>'pdf','name_gu'=>'PDF પાસવર્ડ','name_en'=>'Password Protect','icon'=>'lock','premium'=>0,'engine'=>'pdf-protect',
      'desc_gu'=>'PDF પર પાસવર્ડ લગાવો.','desc_en'=>'Add a password to a PDF.',
      'guide'=>$g('PDF અપલોડ','પાસવર્ડ આપો','પ્રોટેક્ટ','ડાઉનલોડ'),
      'faq'=>[['એન્ક્રિપ્શન?','હા.'],['સુરક્ષિત?','બ્રાઉઝરમાં.'],['ફ્રી?','હા.']]],
    ['slug'=>'pdf-unlock','cat'=>'pdf','name_gu'=>'પાસવર્ડ દૂર','name_en'=>'Password Remove','icon'=>'unlock','premium'=>0,'engine'=>'pdf-unlock',
      'desc_gu'=>'જાણીતા પાસવર્ડ સાથે PDF અનલોક કરો.','desc_en'=>'Unlock PDF with a known password.',
      'guide'=>$g('PDF અપલોડ','પાસવર્ડ આપો','અનલોક','ડાઉનલોડ'),
      'faq'=>[['પાસવર્ડ જરૂરી?','હા.'],['ક્રેક?','ના, કાયદેસર જ.'],['ફ્રી?','હા.']]],
    ['slug'=>'pdf-page-numbers','cat'=>'pdf','name_gu'=>'પેજ નંબર','name_en'=>'Page Numbers','icon'=>'hash','premium'=>0,'engine'=>'pdf-page-num',
      'desc_gu'=>'PDF માં પેજ નંબર ઉમેરો.','desc_en'=>'Add page numbers to a PDF.',
      'guide'=>$g('PDF અપલોડ','પોઝિશન પસંદ','ઉમેરો','ડાઉનલોડ'),
      'faq'=>[['પોઝિશન?','હા.'],['ફોર્મેટ?','1, i, વગેરે.'],['ફ્રી?','હા.']]],
    ['slug'=>'pdf-watermark','cat'=>'pdf','name_gu'=>'PDF વોટરમાર્ક','name_en'=>'PDF Watermark','icon'=>'stamp','premium'=>0,'engine'=>'pdf-watermark',
      'desc_gu'=>'PDF પર ટેક્સ્ટ વોટરમાર્ક ઉમેરો.','desc_en'=>'Add a text watermark to a PDF.',
      'guide'=>$g('PDF અપલોડ','ટેક્સ્ટ આપો','ઓપેસિટી સેટ','ડાઉનલોડ'),
      'faq'=>[['ટેક્સ્ટ?','હા.'],['ઓપેસિટી?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'pdf-metadata','cat'=>'pdf','name_gu'=>'PDF મેટાડેટા','name_en'=>'PDF Metadata Editor','icon'=>'info','premium'=>0,'engine'=>'pdf-metadata',
      'desc_gu'=>'PDF ટાઇટલ/ઓથર વગેરે એડિટ કરો.','desc_en'=>'Edit PDF title/author metadata.',
      'guide'=>$g('PDF અપલોડ','ફીલ્ડ એડિટ','સેવ','ડાઉનલોડ'),
      'faq'=>[['ટાઇટલ?','હા.'],['ઓથર?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'pdf-esign','cat'=>'pdf','name_gu'=>'PDF ઈ-સાઇન','name_en'=>'eSign PDF','icon'=>'pen-tool','premium'=>0,'engine'=>'pdf-esign',
      'desc_gu'=>'PDF પર સહી દોરો કે અપલોડ કરો.','desc_en'=>'Draw or upload a signature on a PDF.',
      'guide'=>$g('PDF અપલોડ','સહી દોરો','પોઝિશન કરો','ડાઉનલોડ'),
      'faq'=>[['દોરી શકાય?','હા.'],['અપલોડ?','હા.'],['ફ્રી?','હા.']]],

    // ─────────────────── C) DOCUMENT / TEXT (14) ───────────────────
    ['slug'=>'excel-to-csv','cat'=>'document','name_gu'=>'Excel થી CSV','name_en'=>'Excel to CSV','icon'=>'table','premium'=>0,'engine'=>'excel-csv','opt'=>['to'=>'csv'],
      'desc_gu'=>'Excel શીટને CSV માં કન્વર્ટ કરો.','desc_en'=>'Convert Excel sheets to CSV.',
      'guide'=>$g('XLSX અપલોડ','શીટ પસંદ','કન્વર્ટ','CSV ડાઉનલોડ'),
      'faq'=>[['બધી શીટ?','એક પસંદ કરો.'],['ડિલિમિટર?','કોમા.'],['ફ્રી?','હા.']]],
    ['slug'=>'csv-to-excel','cat'=>'document','name_gu'=>'CSV થી Excel','name_en'=>'CSV to Excel','icon'=>'table','premium'=>0,'engine'=>'excel-csv','opt'=>['to'=>'xlsx'],
      'desc_gu'=>'CSV ને Excel ફાઇલમાં કન્વર્ટ કરો.','desc_en'=>'Convert CSV to Excel.',
      'guide'=>$g('CSV અપલોડ','પ્રિવ્યૂ','કન્વર્ટ','XLSX ડાઉનલોડ'),
      'faq'=>[['ડિલિમિટર?','ઓટો ડિટેક્ટ.'],['હેડર?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'json-to-excel','cat'=>'document','name_gu'=>'JSON થી Excel','name_en'=>'JSON to Excel','icon'=>'braces','premium'=>0,'engine'=>'json-excel','opt'=>['to'=>'xlsx'],
      'desc_gu'=>'JSON એરેને Excel ટેબલમાં ફેરવો.','desc_en'=>'Convert JSON array to Excel table.',
      'guide'=>$g('JSON પેસ્ટ કરો','પ્રિવ્યૂ','કન્વર્ટ','ડાઉનલોડ'),
      'faq'=>[['નેસ્ટેડ?','ફ્લેટ કરે.'],['એરે?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'excel-to-json','cat'=>'document','name_gu'=>'Excel થી JSON','name_en'=>'Excel to JSON','icon'=>'braces','premium'=>0,'engine'=>'json-excel','opt'=>['to'=>'json'],
      'desc_gu'=>'Excel શીટને JSON માં કન્વર્ટ કરો.','desc_en'=>'Convert Excel to JSON.',
      'guide'=>$g('XLSX અપલોડ','શીટ પસંદ','કન્વર્ટ','JSON કોપી'),
      'faq'=>[['ફોર્મેટ?','એરે ઓફ ઓબ્જેક્ટ.'],['હેડર?','કી બને.'],['ફ્રી?','હા.']]],
    ['slug'=>'json-formatter','cat'=>'document','name_gu'=>'JSON ફોર્મેટર','name_en'=>'JSON Formatter','icon'=>'braces','premium'=>0,'engine'=>'json-format',
      'desc_gu'=>'JSON ને સુંદર ફોર્મેટ કે મિનિફાય કરો.','desc_en'=>'Beautify or minify JSON.',
      'guide'=>$g('JSON પેસ્ટ','ફોર્મેટ/મિનિફાય','વેલિડેટ','કોપી'),
      'faq'=>[['વેલિડેશન?','હા, એરર બતાવે.'],['મિનિફાય?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'xml-json','cat'=>'document','name_gu'=>'XML ↔ JSON','name_en'=>'XML ↔ JSON','icon'=>'code','premium'=>0,'engine'=>'xml-json',
      'desc_gu'=>'XML અને JSON વચ્ચે કન્વર્ટ કરો.','desc_en'=>'Convert between XML and JSON.',
      'guide'=>$g('ડેટા પેસ્ટ','દિશા પસંદ','કન્વર્ટ','કોપી'),
      'faq'=>[['બંને દિશા?','હા.'],['એટ્રિબ્યુટ?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'csv-merger','cat'=>'document','name_gu'=>'CSV મર્જર','name_en'=>'CSV Merger','icon'=>'combine','premium'=>0,'engine'=>'csv-merge',
      'desc_gu'=>'ઘણી CSV ફાઇલોને એકમાં જોડો.','desc_en'=>'Merge multiple CSV files.',
      'guide'=>$g('CSV ફાઇલો પસંદ','હેડર ચેક','મર્જ','ડાઉનલોડ'),
      'faq'=>[['હેડર?','પ્રથમ રાખે.'],['કેટલી?','ઘણી.'],['ફ્રી?','હા.']]],
    ['slug'=>'word-counter','cat'=>'document','name_gu'=>'વર્ડ કાઉન્ટર','name_en'=>'Word Counter','icon'=>'type','premium'=>0,'engine'=>'word-count',
      'desc_gu'=>'શબ્દ, અક્ષર, વાક્ય ગણો.','desc_en'=>'Count words, characters, sentences.',
      'guide'=>$g('ટેક્સ્ટ પેસ્ટ','ગણતરી જુઓ','આંકડા ચેક','કોપી'),
      'faq'=>[['રીઅલ ટાઇમ?','હા.'],['વાંચન સમય?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'case-converter','cat'=>'document','name_gu'=>'કેસ કન્વર્ટર','name_en'=>'Case Converter','icon'=>'case-sensitive','premium'=>0,'engine'=>'case-convert',
      'desc_gu'=>'UPPER, lower, Title કેસ બદલો.','desc_en'=>'Change text case (UPPER/lower/Title).',
      'guide'=>$g('ટેક્સ્ટ પેસ્ટ','કેસ પસંદ','કન્વર્ટ','કોપી'),
      'faq'=>[['કયા કેસ?','5+ પ્રકાર.'],['રીઅલ ટાઇમ?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'find-replace','cat'=>'document','name_gu'=>'ફાઇન્ડ & રિપ્લેસ','name_en'=>'Find & Replace','icon'=>'replace','premium'=>0,'engine'=>'find-replace',
      'desc_gu'=>'ટેક્સ્ટમાં શબ્દ શોધી બદલો.','desc_en'=>'Find and replace text.',
      'guide'=>$g('ટેક્સ્ટ પેસ્ટ','શોધો શબ્દ','બદલો','કોપી'),
      'faq'=>[['રેગેક્સ?','હા.'],['કેસ સેન્સિટિવ?','વિકલ્પ.'],['ફ્રી?','હા.']]],
    ['slug'=>'duplicate-remover','cat'=>'document','name_gu'=>'ડુપ્લિકેટ રિમૂવર','name_en'=>'Duplicate Line Remover','icon'=>'list-x','premium'=>0,'engine'=>'dedupe-lines',
      'desc_gu'=>'ડુપ્લિકેટ લાઇન દૂર કરો.','desc_en'=>'Remove duplicate lines.',
      'guide'=>$g('ટેક્સ્ટ પેસ્ટ','ઓપ્શન પસંદ','પ્રોસેસ','કોપી'),
      'faq'=>[['સોર્ટ?','વિકલ્પ.'],['કેસ?','વિકલ્પ.'],['ફ્રી?','હા.']]],
    ['slug'=>'text-diff','cat'=>'document','name_gu'=>'ટેક્સ્ટ ડિફ','name_en'=>'Text Diff Checker','icon'=>'git-compare','premium'=>0,'engine'=>'text-diff',
      'desc_gu'=>'બે ટેક્સ્ટ વચ્ચેનો ફેર જુઓ.','desc_en'=>'Compare two texts.',
      'guide'=>$g('ટેક્સ્ટ A પેસ્ટ','ટેક્સ્ટ B પેસ્ટ','કમ્પેર','ફેર જુઓ'),
      'faq'=>[['લાઇન ડિફ?','હા.'],['હાઇલાઇટ?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'markdown-to-html','cat'=>'document','name_gu'=>'Markdown થી HTML','name_en'=>'Markdown to HTML','icon'=>'file-code','premium'=>0,'engine'=>'md-html',
      'desc_gu'=>'Markdown ને HTML માં કન્વર્ટ કરો.','desc_en'=>'Convert Markdown to HTML.',
      'guide'=>$g('Markdown પેસ્ટ','પ્રિવ્યૂ જુઓ','HTML કોપી','વાપરો'),
      'faq'=>[['લાઇવ પ્રિવ્યૂ?','હા.'],['ટેબલ?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'html-to-text','cat'=>'document','name_gu'=>'HTML થી ટેક્સ્ટ','name_en'=>'HTML to Text','icon'=>'file-text','premium'=>0,'engine'=>'html-text',
      'desc_gu'=>'HTML ટેગ દૂર કરી પ્લેન ટેક્સ્ટ.','desc_en'=>'Strip HTML tags to plain text.',
      'guide'=>$g('HTML પેસ્ટ','સ્ટ્રિપ કરો','ટેક્સ્ટ કોપી','વાપરો'),
      'faq'=>[['ટેગ દૂર?','હા.'],['લિંક?','રાખવાનો વિકલ્પ.'],['ફ્રી?','હા.']]],

    // ─────────────────── D) CCTV / SECURITY (16) ───────────────────
    ['slug'=>'cctv-storage-calculator','cat'=>'cctv','name_gu'=>'CCTV સ્ટોરેજ કેલ્ક્યુલેટર','name_en'=>'CCTV Storage Calculator','icon'=>'hard-drive','premium'=>0,'engine'=>'cctv-storage',
      'desc_gu'=>'કેમેરા, રિઝોલ્યુશન, દિવસ પ્રમાણે HDD સાઇઝ ગણો.','desc_en'=>'Calculate HDD size from cameras, resolution, retention.',
      'guide'=>$g('કેમેરા સંખ્યા આપો','રિઝોલ્યુશન/FPS પસંદ','દિવસ આપો','GB/TB પરિણામ જુઓ'),
      'faq'=>[['H.265 ફાયદો?','અડધી જગ્યા.'],['ઓડિયો?','થોડું વધારે.'],['ચોકસાઈ?','બિટરેટ આધારિત અંદાજ.']]],
    ['slug'=>'reverse-storage-calculator','cat'=>'cctv','name_gu'=>'રિવર્સ સ્ટોરેજ કેલ્ક','name_en'=>'Reverse Storage Calculator','icon'=>'history','premium'=>0,'engine'=>'cctv-reverse',
      'desc_gu'=>'HDD સાઇઝ પરથી કેટલા દિવસ રેકોર્ડિંગ થાય તે ગણો.','desc_en'=>'From HDD size, find days of recording.',
      'guide'=>$g('HDD સાઇઝ આપો','કેમેરા/રિઝોલ્યુશન','ગણો','દિવસ જુઓ'),
      'faq'=>[['2TB કેટલા દિવસ?','સેટિંગ પર આધાર.'],['ચોકસાઈ?','અંદાજ.'],['ફ્રી?','હા.']]],
    ['slug'=>'cctv-bandwidth-calculator','cat'=>'cctv','name_gu'=>'CCTV બેન્ડવિડ્થ કેલ્ક','name_en'=>'CCTV Bandwidth Calculator','icon'=>'wifi','premium'=>0,'engine'=>'cctv-bandwidth',
      'desc_gu'=>'રિમોટ વ્યૂ માટે જરૂરી Mbps અપલોડ ગણો.','desc_en'=>'Mbps upload needed for remote viewing.',
      'guide'=>$g('કેમેરા/રિઝોલ્યુશન','સ્ટ્રીમ સંખ્યા','ગણો','Mbps જુઓ'),
      'faq'=>[['અપલોડ કેમ?','રિમોટ વ્યૂ માટે.'],['સબ-સ્ટ્રીમ?','ઓછું બેન્ડવિડ્થ.'],['ફ્રી?','હા.']]],
    ['slug'=>'lens-calculator','cat'=>'cctv','name_gu'=>'લેન્સ કેલ્ક્યુલેટર','name_en'=>'Lens / Focal Length Calculator','icon'=>'aperture','premium'=>0,'engine'=>'cctv-lens',
      'desc_gu'=>'અંતર પરથી જરૂરી mm લેન્સ અને FOV ગણો.','desc_en'=>'Find mm lens & FOV from distance.',
      'guide'=>$g('અંતર આપો','સેન્સર સાઇઝ','ગણો','mm/FOV જુઓ'),
      'faq'=>[['mm શું?','ફોકલ લેન્થ.'],['FOV?','દ્રશ્ય કોણ.'],['ફ્રી?','હા.']]],
    ['slug'=>'fov-visualizer','cat'=>'cctv','name_gu'=>'FOV વિઝ્યુલાઇઝર','name_en'=>'Camera Coverage / FOV Visualizer','icon'=>'scan','premium'=>0,'engine'=>'cctv-fov',
      'desc_gu'=>'ફ્લોર પ્લાન પર કેમેરા કવરેજ દોરો.','desc_en'=>'Draw camera coverage on a floor plan.',
      'guide'=>$g('કોણ આપો','રેન્જ આપો','કેમેરા મૂકો','કવરેજ જુઓ'),
      'faq'=>[['કેનવાસ?','હા.'],['કોણ?','એડજસ્ટેબલ.'],['ફ્રી?','હા.']]],
    ['slug'=>'ip-subnet-calculator','cat'=>'cctv','name_gu'=>'IP સબનેટ કેલ્ક','name_en'=>'IP / Subnet Calculator','icon'=>'network','premium'=>0,'engine'=>'ip-subnet',
      'desc_gu'=>'CIDR, usable IP, broadcast ગણો.','desc_en'=>'CIDR, usable IPs, broadcast.',
      'guide'=>$g('IP/CIDR આપો','ગણો','રેન્જ જુઓ','કોપી'),
      'faq'=>[['CIDR?','હા.'],['usable?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'ip-range-planner','cat'=>'cctv','name_gu'=>'NVR IP પ્લાનર','name_en'=>'IP Range Planner for NVR','icon'=>'list-ordered','premium'=>0,'engine'=>'ip-planner',
      'desc_gu'=>'N કેમેરા માટે સ્ટેટિક IP ઓટો-એસાઇન કરો.','desc_en'=>'Auto-assign static IPs for N cameras.',
      'guide'=>$g('શરૂ IP આપો','કેમેરા સંખ્યા','જનરેટ','લિસ્ટ કોપી'),
      'faq'=>[['સ્ટેટિક?','હા.'],['ગેટવે?','બતાવે.'],['ફ્રી?','હા.']]],
    ['slug'=>'poe-calculator','cat'=>'cctv','name_gu'=>'PoE પાવર બજેટ','name_en'=>'PoE Power Budget Calculator','icon'=>'zap','premium'=>0,'engine'=>'poe-budget',
      'desc_gu'=>'સ્વિચ વોટ vs કેમેરા વોટ અને હેડરૂમ ગણો.','desc_en'=>'Switch watts vs camera watts, headroom %.',
      'guide'=>$g('સ્વિચ વોટ આપો','કેમેરા વોટ/સંખ્યા','ગણો','હેડરૂમ જુઓ'),
      'faq'=>[['હેડરૂમ?','સલામતી માર્જિન.'],['PoE+?','30W.'],['ફ્રી?','હા.']]],
    ['slug'=>'cable-length-calculator','cat'=>'cctv','name_gu'=>'કેબલ લેન્થ / વોલ્ટેજ ડ્રોપ','name_en'=>'Cable Length / Voltage Drop','icon'=>'cable','premium'=>0,'engine'=>'cable-drop',
      'desc_gu'=>'Cat6/RG59 મહત્તમ અંતર અને 12V ડ્રોપ ગણો.','desc_en'=>'Cat6/RG59 max distance, 12V drop.',
      'guide'=>$g('કેબલ પ્રકાર','લંબાઈ/વોલ્ટ','ગણો','ડ્રોપ જુઓ'),
      'faq'=>[['Cat6?','100m.'],['12V ડ્રોપ?','ગણે.'],['ફ્રી?','હા.']]],
    ['slug'=>'dvr-channel-planner','cat'=>'cctv','name_gu'=>'DVR/NVR ચેનલ પ્લાનર','name_en'=>'DVR/NVR Channel Planner','icon'=>'layout-grid','premium'=>0,'engine'=>'dvr-planner',
      'desc_gu'=>'એનાલોગ + IP મિક્સ માટે હાઇબ્રિડ ભલામણ.','desc_en'=>'Hybrid recommendation for analog + IP mix.',
      'guide'=>$g('એનાલોગ સંખ્યા','IP સંખ્યા','ગણો','ભલામણ જુઓ'),
      'faq'=>[['હાઇબ્રિડ?','હા.'],['ચેનલ?','ભલામણ.'],['ફ્રી?','હા.']]],
    ['slug'=>'ppm-calculator','cat'=>'cctv','name_gu'=>'PPM / પિક્સેલ ડેન્સિટી','name_en'=>'PPM / Pixel Density Calculator','icon'=>'ruler','premium'=>0,'engine'=>'ppm-calc',
      'desc_gu'=>'ડિટેક્ટ/રેકગ્નાઇઝ/આઇડેન્ટિફાય અંતર ગણો.','desc_en'=>'Detect/recognize/identify distance.',
      'guide'=>$g('રિઝોલ્યુશન આપો','લેન્સ/અંતર','ગણો','PPM જુઓ'),
      'faq'=>[['PPM?','પિક્સેલ પ્રતિ મીટર.'],['આઇડેન્ટિફાય?','250 PPM.'],['ફ્રી?','હા.']]],
    ['slug'=>'cctv-quotation','cat'=>'cctv','name_gu'=>'CCTV કોટેશન જનરેટર','name_en'=>'CCTV Quotation Generator','icon'=>'file-text','premium'=>1,'engine'=>'cctv-quote',
      'desc_gu'=>'કેમેરા/DVR/HDD પસંદ કરી GST સાથે PDF કોટ બનાવો.','desc_en'=>'Build a GST PDF quote on AK Computer letterhead.',
      'guide'=>$g('આઇટમ પસંદ કરો','જથ્થો/ભાવ','GST ઉમેરાય','PDF/WhatsApp'),
      'faq'=>[['GST?','18% ઓટો.'],['લેટરહેડ?','AK Computer.'],['WhatsApp?','હા.']]],
    ['slug'=>'cctv-amc','cat'=>'cctv','name_gu'=>'CCTV AMC કોન્ટ્રાક્ટ','name_en'=>'CCTV AMC Contract Generator','icon'=>'file-check','premium'=>1,'engine'=>'cctv-amc',
      'desc_gu'=>'ક્લાયન્ટ વિગત સાથે વાર્ષિક AMC PDF બનાવો.','desc_en'=>'Generate a yearly AMC contract PDF.',
      'guide'=>$g('ક્લાયન્ટ વિગત','શરતો','રકમ','PDF બનાવો'),
      'faq'=>[['શરતો?','સ્ટાન્ડર્ડ.'],['રકમ?','તમે નક્કી કરો.'],['PDF?','હા.']]],
    ['slug'=>'cctv-password-reference','cat'=>'cctv','name_gu'=>'ડિફોલ્ટ પાસવર્ડ/પોર્ટ','name_en'=>'Default Password / Port Reference','icon'=>'key-round','premium'=>0,'engine'=>'cctv-reference',
      'desc_gu'=>'Hikvision, Dahua, CP Plus ડિફોલ્ટ પોર્ટ ટેબલ.','desc_en'=>'Default ports for major CCTV brands.',
      'guide'=>$g('બ્રાન્ડ પસંદ','પોર્ટ જુઓ','સર્ચ કરો','કોપી'),
      'faq'=>[['સુરક્ષા?','ડિફોલ્ટ બદલો.'],['પોર્ટ?','80/8000/554.'],['ફ્રી?','હા.']]],
    ['slug'=>'camera-time-sync','cat'=>'cctv','name_gu'=>'કેમેરા ટાઇમ સિંક','name_en'=>'Camera Time Sync Helper','icon'=>'clock','premium'=>0,'engine'=>'time-sync',
      'desc_gu'=>'NTP લિસ્ટ, IST ઓફસેટ, epoch↔date, ડ્રિફ્ટ ગણો.','desc_en'=>'NTP list, IST offset, epoch↔date, drift calc.',
      'guide'=>$g('NTP પસંદ','epoch/date','ડ્રિફ્ટ આપો','પરિણામ જુઓ'),
      'faq'=>[['NTP?','હા.'],['IST?','+5:30.'],['ડ્રિફ્ટ?','પ્રતિ દિવસ.']]],
    ['slug'=>'cctv-site-survey','cat'=>'cctv','name_gu'=>'સાઇટ સર્વે ફોર્મ','name_en'=>'CCTV Site Survey Form Generator','icon'=>'clipboard-list','premium'=>0,'engine'=>'site-survey',
      'desc_gu'=>'પ્રિન્ટ કરી શકાય તેવું સાઇટ સર્વે ચેકલિસ્ટ PDF.','desc_en'=>'Printable site survey checklist PDF.',
      'guide'=>$g('વિગત ભરો','આઇટમ ટિક કરો','જનરેટ','PDF/પ્રિન્ટ'),
      'faq'=>[['પ્રિન્ટ?','હા.'],['કસ્ટમ?','હા.'],['ફ્રી?','હા.']]],

    // ─────────────────── E) COMPUTER SHOP (18) ───────────────────
    ['slug'=>'data-storage-converter','cat'=>'computer','name_gu'=>'ડેટા સ્ટોરેજ કન્વર્ટર','name_en'=>'Data Storage Converter','icon'=>'database','premium'=>0,'engine'=>'storage-convert',
      'desc_gu'=>'bit/Byte/KB/MB/GB/TB — 1000 અને 1024 બંને.','desc_en'=>'Convert bit/Byte/KB/MB/GB/TB (1000 & 1024).',
      'guide'=>$g('મૂલ્ય આપો','યુનિટ પસંદ','કન્વર્ટ','પરિણામ કોપી'),
      'faq'=>[['1000 vs 1024?','બંને બતાવે.'],['TB?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'ram-calculator','cat'=>'computer','name_gu'=>'RAM કન્ફિગ કેલ્ક','name_en'=>'RAM Configuration Calculator','icon'=>'memory-stick','premium'=>0,'engine'=>'ram-calc',
      'desc_gu'=>'સ્લોટ, DDR, ડ્યુઅલ-ચેનલ ચેક કરો.','desc_en'=>'Slots, DDR, dual-channel check.',
      'guide'=>$g('સ્લોટ આપો','સ્ટિક સાઇઝ','DDR પસંદ','ચેક કરો'),
      'faq'=>[['ડ્યુઅલ-ચેનલ?','ચેક કરે.'],['DDR5?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'hdd-real-capacity','cat'=>'computer','name_gu'=>'HDD/SSD રિયલ કેપેસિટી','name_en'=>'HDD/SSD Real Capacity','icon'=>'hard-drive','premium'=>0,'engine'=>'hdd-capacity',
      'desc_gu'=>'1TB ડ્રાઇવ = 931GB usable કેમ, તે ગણો.','desc_en'=>'Why 1TB = 931GB usable.',
      'guide'=>$g('સાઇઝ આપો','ગણો','usable જુઓ','સમજો'),
      'faq'=>[['કેમ ઓછું?','1000 vs 1024.'],['SSD?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'partition-planner','cat'=>'computer','name_gu'=>'પાર્ટિશન પ્લાનર','name_en'=>'Partition Planner','icon'=>'pie-chart','premium'=>0,'engine'=>'partition-plan',
      'desc_gu'=>'C/D/E ડ્રાઇવ ભાગલા સૂચવો.','desc_en'=>'Suggest C/D/E partition split.',
      'guide'=>$g('ડ્રાઇવ સાઇઝ','ઉપયોગ પસંદ','ગણો','ભાગલા જુઓ'),
      'faq'=>[['C સાઇઝ?','ભલામણ.'],['કસ્ટમ?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'file-transfer-time','cat'=>'computer','name_gu'=>'ફાઇલ ટ્રાન્સફર ટાઇમ','name_en'=>'File Transfer Time Calculator','icon'=>'timer','premium'=>0,'engine'=>'transfer-time',
      'desc_gu'=>'સાઇઝ ÷ સ્પીડ = સમય ગણો.','desc_en'=>'File size ÷ speed = time.',
      'guide'=>$g('સાઇઝ આપો','સ્પીડ પસંદ','ગણો','સમય જુઓ'),
      'faq'=>[['USB3?','હા.'],['LAN?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'backup-estimator','cat'=>'computer','name_gu'=>'બેકઅપ સાઇઝ એસ્ટિમેટર','name_en'=>'Backup Size Estimator','icon'=>'archive','premium'=>0,'engine'=>'backup-est',
      'desc_gu'=>'બેકઅપ માટે જરૂરી જગ્યા અંદાજો.','desc_en'=>'Estimate backup storage needs.',
      'guide'=>$g('ડેટા સાઇઝ','આવૃત્તિ','ગણો','જગ્યા જુઓ'),
      'faq'=>[['ઇન્ક્રિમેન્ટલ?','હા.'],['કમ્પ્રેશન?','ગણે.'],['ફ્રી?','હા.']]],
    ['slug'=>'psu-calculator','cat'=>'computer','name_gu'=>'PSU વોટેજ કેલ્ક','name_en'=>'PSU Wattage Calculator','icon'=>'power','premium'=>0,'engine'=>'psu-calc',
      'desc_gu'=>'CPU+GPU+HDD પરથી SMPS વોટ ગણો.','desc_en'=>'Recommended SMPS watts from components.',
      'guide'=>$g('કમ્પોનન્ટ પસંદ','જથ્થો','ગણો','વોટ જુઓ'),
      'faq'=>[['હેડરૂમ?','20% ઉમેરે.'],['GPU?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'pc-build-cost','cat'=>'computer','name_gu'=>'PC બિલ્ડ કોસ્ટ','name_en'=>'PC Build Cost Estimator','icon'=>'cpu','premium'=>0,'engine'=>'pc-build',
      'desc_gu'=>'પાર્ટ્સ લિસ્ટ + માર્જિન + GST કુલ.','desc_en'=>'Parts list + margin % + GST.',
      'guide'=>$g('પાર્ટ્સ ઉમેરો','ભાવ આપો','માર્જિન/GST','કુલ જુઓ'),
      'faq'=>[['માર્જિન?','%.'],['GST?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'ups-backup-time','cat'=>'computer','name_gu'=>'UPS બેકઅપ ટાઇમ','name_en'=>'UPS Backup Time Calculator','icon'=>'battery-charging','premium'=>0,'engine'=>'ups-calc',
      'desc_gu'=>'VA, લોડ, બેટરી Ah પરથી મિનિટ ગણો.','desc_en'=>'Minutes from VA, load, battery Ah.',
      'guide'=>$g('VA/લોડ આપો','બેટરી Ah','ગણો','મિનિટ જુઓ'),
      'faq'=>[['Ah?','બેટરી ક્ષમતા.'],['લોડ?','વોટ.'],['ફ્રી?','હા.']]],
    ['slug'=>'screen-ppi-calculator','cat'=>'computer','name_gu'=>'સ્ક્રીન PPI કેલ્ક','name_en'=>'Screen Size / PPI Calculator','icon'=>'monitor','premium'=>0,'engine'=>'ppi-calc',
      'desc_gu'=>'સ્ક્રીન સાઇઝ/રિઝોલ્યુશન/PPI ગણો.','desc_en'=>'Screen size / resolution / PPI.',
      'guide'=>$g('રિઝોલ્યુશન','ઇંચ','ગણો','PPI જુઓ'),
      'faq'=>[['PPI?','પિક્સેલ ડેન્સિટી.'],['રેટિના?','ગણે.'],['ફ્રી?','હા.']]],
    ['slug'=>'aspect-ratio-calculator','cat'=>'computer','name_gu'=>'એસ્પેક્ટ રેશિયો','name_en'=>'Aspect Ratio Calculator','icon'=>'ratio','premium'=>0,'engine'=>'aspect-calc',
      'desc_gu'=>'એસ્પેક્ટ રેશિયો અને નવા ડાયમેન્શન ગણો.','desc_en'=>'Aspect ratio and new dimensions.',
      'guide'=>$g('W×H આપો','નવું W/H','ગણો','પરિણામ જુઓ'),
      'faq'=>[['16:9?','હા.'],['કસ્ટમ?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'printer-page-cost','cat'=>'computer','name_gu'=>'પ્રિન્ટર પેજ કોસ્ટ','name_en'=>'Printer Page Cost Calculator','icon'=>'printer','premium'=>0,'engine'=>'page-cost',
      'desc_gu'=>'કારતૂસ ભાવ ÷ યીલ્ડ = પ્રતિ પેજ ખર્ચ.','desc_en'=>'Cartridge price ÷ yield = cost per page.',
      'guide'=>$g('કારતૂસ ભાવ','યીલ્ડ','ગણો','પ્રતિ પેજ જુઓ'),
      'faq'=>[['યીલ્ડ?','પેજ સંખ્યા.'],['રંગીન?','અલગ.'],['ફ્રી?','હા.']]],
    ['slug'=>'toner-yield-estimator','cat'=>'computer','name_gu'=>'ટોનર યીલ્ડ એસ્ટિમેટર','name_en'=>'Toner/Ink Yield Estimator','icon'=>'droplet','premium'=>0,'engine'=>'toner-est',
      'desc_gu'=>'માસિક પેજ પરથી વર્ષે કારતૂસ ગણો.','desc_en'=>'Cartridges per year from monthly pages.',
      'guide'=>$g('માસિક પેજ','યીલ્ડ','ગણો','વર્ષે જુઓ'),
      'faq'=>[['વર્ષે કેટલા?','ગણે.'],['ખર્ચ?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'download-time-calculator','cat'=>'computer','name_gu'=>'ડાઉનલોડ ટાઇમ કેલ્ક','name_en'=>'Download Time Calculator','icon'=>'download','premium'=>0,'engine'=>'download-time',
      'desc_gu'=>'ઇન્ટરનેટ સ્પીડ પરથી ડાઉનલોડ સમય.','desc_en'=>'Download time from internet speed.',
      'guide'=>$g('સાઇઝ આપો','સ્પીડ Mbps','ગણો','સમય જુઓ'),
      'faq'=>[['Mbps?','હા.'],['ચોકસાઈ?','અંદાજ.'],['ફ્રી?','હા.']]],
    ['slug'=>'video-size-estimator','cat'=>'computer','name_gu'=>'વિડિયો સાઇઝ એસ્ટિમેટર','name_en'=>'Video File Size Estimator','icon'=>'film','premium'=>0,'engine'=>'video-size',
      'desc_gu'=>'બિટરેટ × સમય = વિડિયો સાઇઝ.','desc_en'=>'Bitrate × duration = file size.',
      'guide'=>$g('બિટરેટ આપો','સમય','ગણો','સાઇઝ જુઓ'),
      'faq'=>[['બિટરેટ?','Mbps.'],['4K?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'mbps-converter','cat'=>'computer','name_gu'=>'Mbps ↔ MB/s','name_en'=>'Mbps ↔ MB/s Converter','icon'=>'gauge','premium'=>0,'engine'=>'mbps-convert',
      'desc_gu'=>'Mbps અને MB/s વચ્ચે કન્વર્ટ કરો.','desc_en'=>'Convert Mbps and MB/s.',
      'guide'=>$g('મૂલ્ય આપો','યુનિટ પસંદ','કન્વર્ટ','જુઓ'),
      'faq'=>[['ફેર?','8 ગણો.'],['ઇન્ટરનેટ?','Mbps.'],['ફ્રી?','હા.']]],
    ['slug'=>'barcode-generator','cat'=>'computer','name_gu'=>'બારકોડ જનરેટર','name_en'=>'Barcode Generator','icon'=>'scan-barcode','premium'=>0,'engine'=>'barcode-gen',
      'desc_gu'=>'ઇન્વેન્ટરી માટે Code128/EAN13 બારકોડ.','desc_en'=>'Code128/EAN13 barcodes for inventory.',
      'guide'=>$g('ટેક્સ્ટ આપો','ફોર્મેટ પસંદ','જનરેટ','ડાઉનલોડ'),
      'faq'=>[['EAN13?','હા.'],['પ્રિન્ટ?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'job-sheet-generator','cat'=>'computer','name_gu'=>'સર્વિસ જોબ શીટ','name_en'=>'Service Job Sheet Generator','icon'=>'wrench','premium'=>0,'engine'=>'job-sheet',
      'desc_gu'=>'રિપેર ટોકન PDF + WhatsApp ગ્રાહકને.','desc_en'=>'Repair token PDF + WhatsApp to customer.',
      'guide'=>$g('ગ્રાહક વિગત','ડિવાઇસ/સમસ્યા','અંદાજ','PDF/WhatsApp'),
      'faq'=>[['ટોકન?','ઓટો નંબર.'],['WhatsApp?','હા.'],['ફ્રી?','હા.']]],

    // ─────────────────── F) BUSINESS / SHOP (12) ───────────────────
    ['slug'=>'gst-calculator','cat'=>'business','name_gu'=>'GST કેલ્ક્યુલેટર','name_en'=>'GST Calculator','icon'=>'percent','premium'=>0,'engine'=>'gst-calc',
      'desc_gu'=>'inclusive/exclusive, CGST-SGST-IGST સ્પ્લિટ.','desc_en'=>'Inclusive/exclusive, CGST-SGST-IGST split.',
      'guide'=>$g('રકમ આપો','GST % પસંદ','પ્રકાર પસંદ','ગણો'),
      'faq'=>[['5/12/18/28%?','હા.'],['સ્પ્લિટ?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'invoice-generator','cat'=>'business','name_gu'=>'ઇન્વોઇસ જનરેટર','name_en'=>'Invoice Generator','icon'=>'receipt','premium'=>1,'engine'=>'invoice-gen',
      'desc_gu'=>'GST ટેક્સ ઇન્વોઇસ PDF, HSN, લોગો સાથે.','desc_en'=>'GST tax invoice PDF with HSN & logo.',
      'guide'=>$g('ગ્રાહક વિગત','આઇટમ ઉમેરો','GST/HSN','PDF બનાવો'),
      'faq'=>[['HSN?','હા.'],['સેવ?','હા DB માં.'],['WhatsApp?','હા.']]],
    ['slug'=>'quotation-generator','cat'=>'business','name_gu'=>'કોટેશન જનરેટર','name_en'=>'Quotation Generator','icon'=>'file-text','premium'=>0,'engine'=>'quote-gen',
      'desc_gu'=>'સામાન્ય કોટેશન PDF બનાવો.','desc_en'=>'Generate a general quotation PDF.',
      'guide'=>$g('વિગત આપો','આઇટમ','કુલ','PDF'),
      'faq'=>[['GST?','વિકલ્પ.'],['PDF?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'emi-calculator','cat'=>'business','name_gu'=>'EMI કેલ્ક્યુલેટર','name_en'=>'EMI Calculator','icon'=>'landmark','premium'=>0,'engine'=>'emi-calc',
      'desc_gu'=>'લોન EMI + એમોર્ટાઇઝેશન ટેબલ.','desc_en'=>'Loan EMI + amortization table.',
      'guide'=>$g('રકમ આપો','વ્યાજ/મુદત','ગણો','ટેબલ જુઓ'),
      'faq'=>[['ટેબલ?','હા.'],['ચાર્ટ?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'margin-calculator','cat'=>'business','name_gu'=>'પ્રોફિટ માર્જિન','name_en'=>'Profit Margin / Markup','icon'=>'trending-up','premium'=>0,'engine'=>'margin-calc',
      'desc_gu'=>'કોસ્ટ પરથી ટાર્ગેટ % એ MRP ગણો.','desc_en'=>'Cost → MRP at target margin %.',
      'guide'=>$g('કોસ્ટ આપો','માર્જિન %','ગણો','MRP જુઓ'),
      'faq'=>[['માર્જિન vs માર્કઅપ?','બંને.'],['GST?','વિકલ્પ.'],['ફ્રી?','હા.']]],
    ['slug'=>'discount-calculator','cat'=>'business','name_gu'=>'ડિસ્કાઉન્ટ કેલ્ક','name_en'=>'Discount Calculator','icon'=>'tag','premium'=>0,'engine'=>'discount-calc',
      'desc_gu'=>'ડિસ્કાઉન્ટ પછીની કિંમત ગણો.','desc_en'=>'Price after discount.',
      'guide'=>$g('MRP આપો','ડિસ્કાઉન્ટ %','ગણો','બચત જુઓ'),
      'faq'=>[['મલ્ટિપલ?','હા.'],['બચત?','બતાવે.'],['ફ્રી?','હા.']]],
    ['slug'=>'currency-converter','cat'=>'business','name_gu'=>'કરન્સી કન્વર્ટર','name_en'=>'Currency Converter','icon'=>'coins','premium'=>0,'engine'=>'currency-convert',
      'desc_gu'=>'લાઇવ રેટ + મેન્યુઅલ ફોલબેક.','desc_en'=>'Live rate + manual fallback.',
      'guide'=>$g('રકમ આપો','કરન્સી પસંદ','કન્વર્ટ','જુઓ'),
      'faq'=>[['લાઇવ?','API.'],['ફોલબેક?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'warranty-tracker','cat'=>'business','name_gu'=>'વોરંટી ટ્રેકર','name_en'=>'Warranty Expiry Tracker','icon'=>'shield-check','premium'=>0,'engine'=>'warranty-calc',
      'desc_gu'=>'ખરીદી + મહિના = એક્સપાયરી + બાકી દિવસ.','desc_en'=>'Purchase + months = expiry + days left.',
      'guide'=>$g('ખરીદી તારીખ','મહિના','ગણો','એક્સપાયરી જુઓ'),
      'faq'=>[['બાકી દિવસ?','હા.'],['રિમાઇન્ડર?','પ્રીમિયમ.'],['ફ્રી?','હા.']]],
    ['slug'=>'amc-renewal-calculator','cat'=>'business','name_gu'=>'AMC રિન્યુઅલ ડેટ','name_en'=>'AMC Renewal Date Calculator','icon'=>'calendar-clock','premium'=>0,'engine'=>'amc-calc',
      'desc_gu'=>'AMC શરૂ તારીખ પરથી રિન્યુઅલ તારીખ.','desc_en'=>'Renewal date from AMC start.',
      'guide'=>$g('શરૂ તારીખ','મુદત','ગણો','રિન્યુઅલ જુઓ'),
      'faq'=>[['રિમાઇન્ડર?','હા.'],['મુદત?','1/2/3 વર્ષ.'],['ફ્રી?','હા.']]],
    ['slug'=>'salary-calculator','cat'=>'business','name_gu'=>'સેલરી કેલ્ક્યુલેટર','name_en'=>'Salary/Payroll Calculator','icon'=>'wallet','premium'=>0,'engine'=>'salary-calc',
      'desc_gu'=>'basic, HRA, PF, ESI ગણો.','desc_en'=>'Basic, HRA, PF, ESI breakdown.',
      'guide'=>$g('CTC આપો','ઘટક %','ગણો','બ્રેકઅપ જુઓ'),
      'faq'=>[['PF?','12%.'],['ESI?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'purchase-order','cat'=>'business','name_gu'=>'પર્ચેઝ ઓર્ડર','name_en'=>'Purchase Order Generator','icon'=>'shopping-cart','premium'=>0,'engine'=>'po-gen',
      'desc_gu'=>'સપ્લાયર માટે PO PDF બનાવો.','desc_en'=>'Generate a purchase order PDF.',
      'guide'=>$g('સપ્લાયર વિગત','આઇટમ','કુલ','PDF'),
      'faq'=>[['PDF?','હા.'],['GST?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'inventory-valuation','cat'=>'business','name_gu'=>'સ્ટોક વેલ્યુએશન','name_en'=>'Inventory Valuation Calculator','icon'=>'boxes','premium'=>0,'engine'=>'inventory-calc',
      'desc_gu'=>'સ્ટોકનું કુલ મૂલ્ય ગણો.','desc_en'=>'Calculate total stock value.',
      'guide'=>$g('આઇટમ ઉમેરો','જથ્થો/ભાવ','ગણો','કુલ જુઓ'),
      'faq'=>[['FIFO?','સાદું.'],['કુલ?','હા.'],['ફ્રી?','હા.']]],

    // ─────────────────── G) DATE / TIME / MATH (10) ───────────────────
    ['slug'=>'days-calculator','cat'=>'datetime','name_gu'=>'ટોટલ ડેઝ કેલ્ક','name_en'=>'Total Days Calculator','icon'=>'calendar-days','premium'=>0,'engine'=>'days-calc',
      'desc_gu'=>'બે તારીખ વચ્ચે દિવસ/અઠવાડિયા/વર્કિંગ ડે.','desc_en'=>'Days/weeks/working days between dates.',
      'guide'=>$g('તારીખ 1','તારીખ 2','ગણો','પરિણામ જુઓ'),
      'faq'=>[['વર્કિંગ ડે?','રવિ બાદ.'],['રજા?','ભારત.'],['ફ્રી?','હા.']]],
    ['slug'=>'age-calculator','cat'=>'datetime','name_gu'=>'ઉંમર કેલ્ક્યુલેટર','name_en'=>'Age Calculator','icon'=>'cake','premium'=>0,'engine'=>'age-calc',
      'desc_gu'=>'Y/M/D ઉંમર + આગામી જન્મદિવસ કાઉન્ટડાઉન.','desc_en'=>'Age in Y/M/D + next birthday.',
      'guide'=>$g('જન્મ તારીખ','ગણો','ઉંમર જુઓ','કાઉન્ટડાઉન'),
      'faq'=>[['ચોક્કસ?','હા.'],['જન્મદિવસ?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'date-add-subtract','cat'=>'datetime','name_gu'=>'ડેટ એડ/સબટ્રેક્ટ','name_en'=>'Date Add/Subtract','icon'=>'calendar-plus','premium'=>0,'engine'=>'date-math',
      'desc_gu'=>'તારીખમાં દિવસ/મહિના ઉમેરો કે બાદ કરો.','desc_en'=>'Add or subtract days/months from a date.',
      'guide'=>$g('તારીખ આપો','દિવસ/મહિના','ઉમેરો/બાદ','જુઓ'),
      'faq'=>[['મહિના?','હા.'],['વર્ષ?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'working-days-calculator','cat'=>'datetime','name_gu'=>'વર્કિંગ ડેઝ કેલ્ક','name_en'=>'Working Days Calculator','icon'=>'briefcase','premium'=>0,'engine'=>'working-days',
      'desc_gu'=>'રજા બાદ કરીને કામકાજના દિવસ ગણો.','desc_en'=>'Working days excluding holidays.',
      'guide'=>$g('તારીખ રેન્જ','રજા પસંદ','ગણો','જુઓ'),
      'faq'=>[['રવિ?','બાદ.'],['રજા?','ભારત.'],['ફ્રી?','હા.']]],
    ['slug'=>'epoch-converter','cat'=>'datetime','name_gu'=>'Epoch ↔ Date','name_en'=>'Timestamp/Epoch Converter','icon'=>'clock','premium'=>0,'engine'=>'epoch-convert',
      'desc_gu'=>'Unix ટાઇમસ્ટેમ્પ અને તારીખ કન્વર્ટ.','desc_en'=>'Convert Unix timestamp and date.',
      'guide'=>$g('epoch/date આપો','કન્વર્ટ','જુઓ','કોપી'),
      'faq'=>[['ms?','હા.'],['TZ?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'timezone-converter','cat'=>'datetime','name_gu'=>'ટાઇમ ઝોન કન્વર્ટર','name_en'=>'Time Zone Converter','icon'=>'globe','premium'=>0,'engine'=>'tz-convert',
      'desc_gu'=>'IST સાથે અન્ય ટાઇમ ઝોન સરખાવો.','desc_en'=>'Compare time zones with IST.',
      'guide'=>$g('સમય આપો','ઝોન પસંદ','કન્વર્ટ','જુઓ'),
      'faq'=>[['IST?','બેઝ.'],['DST?','ગણે.'],['ફ્રી?','હા.']]],
    ['slug'=>'countdown-timer','cat'=>'datetime','name_gu'=>'કાઉન્ટડાઉન / સ્ટોપવોચ','name_en'=>'Countdown Timer / Stopwatch','icon'=>'timer','premium'=>0,'engine'=>'timer-tool',
      'desc_gu'=>'કાઉન્ટડાઉન અને સ્ટોપવોચ ટાઇમર.','desc_en'=>'Countdown and stopwatch.',
      'guide'=>$g('મોડ પસંદ','સમય સેટ','શરૂ કરો','જુઓ'),
      'faq'=>[['એલાર્મ?','હા.'],['લેપ?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'unit-converter','cat'=>'datetime','name_gu'=>'યુનિટ કન્વર્ટર','name_en'=>'Unit Converter','icon'=>'ruler','premium'=>0,'engine'=>'unit-convert',
      'desc_gu'=>'લંબાઈ/વજન/તાપમાન/વિસ્તાર/વોલ્યુમ.','desc_en'=>'Length/weight/temp/area/volume.',
      'guide'=>$g('શ્રેણી પસંદ','મૂલ્ય આપો','યુનિટ','કન્વર્ટ'),
      'faq'=>[['શ્રેણી?','5+.'],['ચોક્કસ?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'percentage-calculator','cat'=>'datetime','name_gu'=>'ટકાવારી કેલ્ક','name_en'=>'Percentage Calculator','icon'=>'percent','premium'=>0,'engine'=>'percent-calc',
      'desc_gu'=>'ટકાવારીના બધા પ્રકારના ગણતરી.','desc_en'=>'All percentage calculations.',
      'guide'=>$g('પ્રકાર પસંદ','મૂલ્ય આપો','ગણો','જુઓ'),
      'faq'=>[['વધારો/ઘટાડો?','હા.'],['of?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'scientific-calculator','cat'=>'datetime','name_gu'=>'સાયન્ટિફિક કેલ્ક','name_en'=>'Scientific Calculator','icon'=>'calculator','premium'=>0,'engine'=>'sci-calc',
      'desc_gu'=>'ટ્રિગ, લોગ, પાવર સાથે વૈજ્ઞાનિક કેલ્ક.','desc_en'=>'Scientific calc with trig, log, powers.',
      'guide'=>$g('એક્સપ્રેશન','ફંક્શન','=','જુઓ'),
      'faq'=>[['ટ્રિગ?','હા.'],['મેમરી?','હા.'],['ફ્રી?','હા.']]],

    // ─────────────────── H) DEVELOPER / MISC (8) ───────────────────
    ['slug'=>'qr-generator','cat'=>'developer','name_gu'=>'QR કોડ જનરેટર','name_en'=>'QR Code Generator','icon'=>'qr-code','premium'=>0,'engine'=>'qr-gen',
      'desc_gu'=>'URL/WiFi/vCard/UPI QR કોડ, સેન્ટર લોગો સાથે.','desc_en'=>'URL/WiFi/vCard/UPI QR with center logo.',
      'guide'=>$g('પ્રકાર પસંદ','ડેટા આપો','જનરેટ','ડાઉનલોડ'),
      'faq'=>[['UPI?','હા.'],['લોગો?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'qr-scanner','cat'=>'developer','name_gu'=>'QR કોડ સ્કેનર','name_en'=>'QR Code Scanner','icon'=>'scan-line','premium'=>0,'engine'=>'qr-scan',
      'desc_gu'=>'કેમેરા કે ઇમેજથી QR સ્કેન કરો.','desc_en'=>'Scan QR via camera or image.',
      'guide'=>$g('કેમેરા/ઇમેજ','સ્કેન','પરિણામ જુઓ','કોપી'),
      'faq'=>[['કેમેરા?','હા.'],['ઇમેજ?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'password-generator','cat'=>'developer','name_gu'=>'પાસવર્ડ જનરેટર','name_en'=>'Password Generator','icon'=>'key-round','premium'=>0,'engine'=>'password-gen',
      'desc_gu'=>'મજબૂત પાસવર્ડ + સ્ટ્રેન્થ મીટર.','desc_en'=>'Strong password + strength meter.',
      'guide'=>$g('લંબાઈ પસંદ','વિકલ્પ','જનરેટ','કોપી'),
      'faq'=>[['મજબૂત?','હા.'],['સ્ટ્રેન્થ?','બતાવે.'],['ફ્રી?','હા.']]],
    ['slug'=>'hash-generator','cat'=>'developer','name_gu'=>'હેશ જનરેટર','name_en'=>'Hash Generator','icon'=>'fingerprint','premium'=>0,'engine'=>'hash-gen',
      'desc_gu'=>'MD5/SHA1/SHA256 હેશ બનાવો.','desc_en'=>'Generate MD5/SHA1/SHA256 hashes.',
      'guide'=>$g('ટેક્સ્ટ આપો','અલ્ગોરિધમ','જનરેટ','કોપી'),
      'faq'=>[['SHA256?','હા.'],['ફાઇલ?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'base64-encoder','cat'=>'developer','name_gu'=>'Base64 એન્કોડર','name_en'=>'Base64 Encoder/Decoder','icon'=>'binary','premium'=>0,'engine'=>'base64-tool',
      'desc_gu'=>'ટેક્સ્ટને Base64 એન્કોડ/ડીકોડ કરો.','desc_en'=>'Encode/decode Base64 text.',
      'guide'=>$g('ટેક્સ્ટ પેસ્ટ','એન્કોડ/ડીકોડ','પરિણામ','કોપી'),
      'faq'=>[['ડીકોડ?','હા.'],['UTF-8?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'url-encoder','cat'=>'developer','name_gu'=>'URL એન્કોડર','name_en'=>'URL Encoder/Decoder','icon'=>'link','premium'=>0,'engine'=>'url-tool',
      'desc_gu'=>'URL એન્કોડ/ડીકોડ કરો.','desc_en'=>'Encode/decode URLs.',
      'guide'=>$g('URL પેસ્ટ','એન્કોડ/ડીકોડ','પરિણામ','કોપી'),
      'faq'=>[['સ્પેશિયલ?','હા.'],['ડીકોડ?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'lorem-ipsum','cat'=>'developer','name_gu'=>'લોરેમ ઇપ્સમ','name_en'=>'Lorem Ipsum Generator','icon'=>'text','premium'=>0,'engine'=>'lorem-gen',
      'desc_gu'=>'ડમી ટેક્સ્ટ (અંગ્રેજી + ગુજરાતી) બનાવો.','desc_en'=>'Dummy text (English + Gujarati).',
      'guide'=>$g('પ્રકાર પસંદ','સંખ્યા','જનરેટ','કોપી'),
      'faq'=>[['ગુજરાતી?','હા.'],['ફકરા?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'wifi-qr-card','cat'=>'developer','name_gu'=>'WiFi QR કાર્ડ','name_en'=>'WiFi QR Card Generator','icon'=>'wifi','premium'=>0,'engine'=>'wifi-qr',
      'desc_gu'=>'શોપ/ગ્રાહક માટે પ્રિન્ટ કરી શકાય તેવું WiFi QR કાર્ડ.','desc_en'=>'Printable WiFi QR card.',
      'guide'=>$g('SSID/પાસવર્ડ','સિક્યુરિટી','જનરેટ','પ્રિન્ટ'),
      'faq'=>[['ઓટો કનેક્ટ?','સ્કેનથી.'],['પ્રિન્ટ?','હા.'],['ફ્રી?','હા.']]],

    // ─────────────── I) DEVELOPER / API TOOLS (28) ───────────────
    ['slug'=>'api-tester','cat'=>'devtools','name_gu'=>'API / REST ટેસ્ટર','name_en'=>'API / REST Client','icon'=>'send','premium'=>0,'engine'=>'api-tester',
      'desc_gu'=>'કોઈપણ REST API પર GET/POST/PUT/DELETE રિક્વેસ્ટ મોકલો અને રિસ્પોન્સ જુઓ.','desc_en'=>'Send GET/POST/PUT/DELETE requests to any REST API and inspect the response.',
      'guide'=>$g('મેથડ અને URL આપો','હેડર/બોડી ઉમેરો','Send દબાવો','સ્ટેટસ, હેડર, બોડી જુઓ'),
      'faq'=>[['CORS પ્રોબ્લેમ?','સર્વર પ્રોક્સી થી બાયપાસ થાય.'],['સુરક્ષિત?','પ્રાઇવેટ IP બ્લોક કરેલ છે.'],['ફ્રી?','હા.']]],
    ['slug'=>'webhook-tester','cat'=>'devtools','name_gu'=>'વેબહૂક ટેસ્ટર','name_en'=>'Webhook Tester','icon'=>'webhook','premium'=>0,'engine'=>'webhook-tester',
      'desc_gu'=>'એક યુનિક URL મેળવો, ત્યાં આવતી વેબહૂક રિક્વેસ્ટ લાઇવ જુઓ.','desc_en'=>'Get a unique URL and inspect incoming webhook requests live.',
      'guide'=>$g('યુનિક URL બનાવો','તમારી સર્વિસમાં પેસ્ટ કરો','રિક્વેસ્ટ મોકલાવો','આવેલ ડેટા જુઓ'),
      'faq'=>[['કેટલો સમય?','24 કલાક સુધી.'],['હેડર દેખાય?','હા, બોડી પણ.'],['ફ્રી?','હા.']]],
    ['slug'=>'jwt-decoder','cat'=>'devtools','name_gu'=>'JWT ડીકોડર','name_en'=>'JWT Decoder & Verifier','icon'=>'key-round','premium'=>0,'engine'=>'jwt-decoder',
      'desc_gu'=>'JWT ટોકનનું header, payload ડીકોડ કરો અને signature વેરિફાય કરો.','desc_en'=>'Decode JWT header/payload and verify the HS256 signature.',
      'guide'=>$g('JWT પેસ્ટ કરો','header/payload જુઓ','secret આપો','વેરિફાય કરો'),
      'faq'=>[['સર્વર પર જાય?','ના, બ્રાઉઝરમાં જ.'],['HS256?','હા verify થાય.'],['ફ્રી?','હા.']]],
    ['slug'=>'jwt-generator','cat'=>'devtools','name_gu'=>'JWT જનરેટર','name_en'=>'JWT Generator','icon'=>'key-square','premium'=>0,'engine'=>'jwt-gen',
      'desc_gu'=>'payload અને secret થી HS256 JWT ટોકન બનાવો.','desc_en'=>'Create an HS256 JWT from a payload and secret.',
      'guide'=>$g('payload JSON લખો','secret આપો','જનરેટ કરો','ટોકન કોપી કરો'),
      'faq'=>[['અલ્ગોરિધમ?','HS256.'],['સુરક્ષિત?','બ્રાઉઝરમાં જ.'],['ફ્રી?','હા.']]],
    ['slug'=>'regex-tester','cat'=>'devtools','name_gu'=>'Regex ટેસ્ટર','name_en'=>'Regex Tester','icon'=>'regex','premium'=>0,'engine'=>'regex-tester',
      'desc_gu'=>'રેગ્યુલર એક્સપ્રેશન લાઇવ ટેસ્ટ કરો, મેચ હાઇલાઇટ જુઓ.','desc_en'=>'Test regular expressions live with match highlighting.',
      'guide'=>$g('પેટર્ન લખો','ફ્લેગ પસંદ કરો','ટેક્સ્ટ પેસ્ટ','મેચ જુઓ'),
      'faq'=>[['ગ્રુપ દેખાય?','હા.'],['ફ્લેગ?','g,i,m વગેરે.'],['ફ્રી?','હા.']]],
    ['slug'=>'cron-parser','cat'=>'devtools','name_gu'=>'Cron પાર્સર','name_en'=>'Cron Expression Parser','icon'=>'timer','premium'=>0,'engine'=>'cron-parser',
      'desc_gu'=>'cron એક્સપ્રેશનનો અર્થ અને આગામી રન ટાઇમ જુઓ.','desc_en'=>'Explain a cron expression and show next run times.',
      'guide'=>$g('cron લખો','અર્થ વાંચો','આગામી રન જુઓ','કોપી કરો'),
      'faq'=>[['5 ફીલ્ડ?','હા.'],['આગામી રન?','બતાવે.'],['ફ્રી?','હા.']]],
    ['slug'=>'uuid-generator','cat'=>'devtools','name_gu'=>'UUID જનરેટર','name_en'=>'UUID / ULID Generator','icon'=>'fingerprint','premium'=>0,'engine'=>'uuid-gen',
      'desc_gu'=>'UUID v4 અને ULID બલ્કમાં જનરેટ કરો.','desc_en'=>'Generate UUID v4 and ULID in bulk.',
      'guide'=>$g('પ્રકાર પસંદ','સંખ્યા આપો','જનરેટ','કોપી'),
      'faq'=>[['v4?','હા random.'],['ULID?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'json-yaml','cat'=>'devtools','name_gu'=>'JSON ↔ YAML','name_en'=>'JSON ↔ YAML Converter','icon'=>'file-json','premium'=>0,'engine'=>'json-yaml',
      'desc_gu'=>'JSON અને YAML વચ્ચે કન્વર્ટ કરો.','desc_en'=>'Convert between JSON and YAML.',
      'guide'=>$g('ડેટા પેસ્ટ','દિશા પસંદ','કન્વર્ટ','કોપી'),
      'faq'=>[['બંને દિશા?','હા.'],['વેલિડેશન?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'json-to-typescript','cat'=>'devtools','name_gu'=>'JSON થી TypeScript','name_en'=>'JSON to TypeScript','icon'=>'file-code-2','premium'=>0,'engine'=>'json-ts',
      'desc_gu'=>'JSON પરથી TypeScript interface બનાવો.','desc_en'=>'Generate TypeScript interfaces from JSON.',
      'guide'=>$g('JSON પેસ્ટ','જનરેટ','interface જુઓ','કોપી'),
      'faq'=>[['નેસ્ટેડ?','હા.'],['એરે?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'sql-formatter','cat'=>'devtools','name_gu'=>'SQL ફોર્મેટર','name_en'=>'SQL Formatter','icon'=>'database','premium'=>0,'engine'=>'sql-format',
      'desc_gu'=>'SQL ક્વેરી સુંદર ફોર્મેટ કરો.','desc_en'=>'Beautify and format SQL queries.',
      'guide'=>$g('SQL પેસ્ટ','ફોર્મેટ','જુઓ','કોપી'),
      'faq'=>[['કીવર્ડ કેપિટલ?','હા.'],['મિનિફાય?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'http-status-codes','cat'=>'devtools','name_gu'=>'HTTP સ્ટેટસ કોડ','name_en'=>'HTTP Status Codes','icon'=>'list','premium'=>0,'engine'=>'http-status',
      'desc_gu'=>'બધા HTTP સ્ટેટસ કોડનો અર્થ શોધો.','desc_en'=>'Look up the meaning of any HTTP status code.',
      'guide'=>$g('કોડ સર્ચ કરો','અર્થ જુઓ','શ્રેણી પસંદ','વાપરો'),
      'faq'=>[['404?','Not Found.'],['500?','Server Error.'],['ફ્રી?','હા.']]],
    ['slug'=>'mime-types','cat'=>'devtools','name_gu'=>'MIME ટાઇપ લુકઅપ','name_en'=>'MIME Type Lookup','icon'=>'file-search','premium'=>0,'engine'=>'mime-lookup',
      'desc_gu'=>'ફાઇલ એક્સટેન્શનનો MIME ટાઇપ શોધો.','desc_en'=>'Find the MIME type for any file extension.',
      'guide'=>$g('એક્સટેન્શન લખો','MIME જુઓ','સર્ચ','કોપી'),
      'faq'=>[['.pdf?','application/pdf.'],['.json?','application/json.'],['ફ્રી?','હા.']]],
    ['slug'=>'user-agent-parser','cat'=>'devtools','name_gu'=>'User Agent પાર્સર','name_en'=>'User Agent Parser','icon'=>'monitor-smartphone','premium'=>0,'engine'=>'ua-parser',
      'desc_gu'=>'User-Agent સ્ટ્રિંગમાંથી બ્રાઉઝર/OS/ડિવાઇસ કાઢો.','desc_en'=>'Parse browser, OS and device from a User-Agent string.',
      'guide'=>$g('UA પેસ્ટ કરો','પાર્સ કરો','વિગત જુઓ','કોપી'),
      'faq'=>[['મારું UA?','ઓટો ભરાય.'],['ડિવાઇસ?','બતાવે.'],['ફ્રી?','હા.']]],
    ['slug'=>'my-ip','cat'=>'devtools','name_gu'=>'મારું IP','name_en'=>'What Is My IP','icon'=>'globe','premium'=>0,'engine'=>'my-ip',
      'desc_gu'=>'તમારું પબ્લિક IP અને રિક્વેસ્ટ હેડર જુઓ.','desc_en'=>'See your public IP address and request headers.',
      'guide'=>$g('પેજ ખોલો','IP જુઓ','હેડર જુઓ','કોપી'),
      'faq'=>[['IPv6?','હોય તો બતાવે.'],['હેડર?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'dns-lookup','cat'=>'devtools','name_gu'=>'DNS લુકઅપ','name_en'=>'DNS Lookup','icon'=>'network','premium'=>0,'engine'=>'dns-lookup',
      'desc_gu'=>'ડોમેનના A, MX, TXT, NS, CNAME રેકોર્ડ જુઓ.','desc_en'=>'Look up A, MX, TXT, NS and CNAME records for a domain.',
      'guide'=>$g('ડોમેન લખો','રેકોર્ડ પ્રકાર પસંદ','લુકઅપ','પરિણામ જુઓ'),
      'faq'=>[['MX?','હા.'],['TXT?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'html-minifier','cat'=>'devtools','name_gu'=>'HTML મિનિફાયર','name_en'=>'HTML Minifier','icon'=>'minimize-2','premium'=>0,'engine'=>'html-min',
      'desc_gu'=>'HTML કોડ મિનિફાય કરી સાઇઝ ઘટાડો.','desc_en'=>'Minify HTML to reduce size.',
      'guide'=>$g('HTML પેસ્ટ','મિનિફાય','સેવ્ડ % જુઓ','કોપી'),
      'faq'=>[['કોમેન્ટ દૂર?','હા.'],['સ્પેસ?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'css-minifier','cat'=>'devtools','name_gu'=>'CSS મિનિફાયર','name_en'=>'CSS Minifier','icon'=>'minimize-2','premium'=>0,'engine'=>'css-min',
      'desc_gu'=>'CSS મિનિફાય કરો.','desc_en'=>'Minify CSS code.',
      'guide'=>$g('CSS પેસ્ટ','મિનિફાય','જુઓ','કોપી'),
      'faq'=>[['કોમેન્ટ?','દૂર.'],['સેવિંગ?','બતાવે.'],['ફ્રી?','હા.']]],
    ['slug'=>'js-minifier','cat'=>'devtools','name_gu'=>'JS મિનિફાયર','name_en'=>'JavaScript Minifier','icon'=>'minimize-2','premium'=>0,'engine'=>'js-min',
      'desc_gu'=>'JavaScript મિનિફાય કરો.','desc_en'=>'Minify JavaScript code.',
      'guide'=>$g('JS પેસ્ટ','મિનિફાય','જુઓ','કોપી'),
      'faq'=>[['કોમેન્ટ?','દૂર.'],['સ્પેસ?','દૂર.'],['ફ્રી?','હા.']]],
    ['slug'=>'code-beautifier','cat'=>'devtools','name_gu'=>'કોડ બ્યુટીફાયર','name_en'=>'Code Beautifier','icon'=>'braces','premium'=>0,'engine'=>'code-beautify',
      'desc_gu'=>'HTML/CSS/JS કોડ સુંદર ફોર્મેટ કરો.','desc_en'=>'Beautify HTML, CSS and JS code.',
      'guide'=>$g('કોડ પેસ્ટ','ભાષા પસંદ','બ્યુટીફાય','કોપી'),
      'faq'=>[['ઇન્ડેન્ટ?','હા.'],['ભાષા?','3.'],['ફ્રી?','હા.']]],
    ['slug'=>'slugify','cat'=>'devtools','name_gu'=>'સ્લગ જનરેટર','name_en'=>'Slug Generator','icon'=>'link','premium'=>0,'engine'=>'slugify',
      'desc_gu'=>'ટેક્સ્ટને URL-ફ્રેન્ડલી slug માં ફેરવો.','desc_en'=>'Convert text into a URL-friendly slug.',
      'guide'=>$g('ટેક્સ્ટ લખો','ઓપ્શન પસંદ','જનરેટ','કોપી'),
      'faq'=>[['સ્પેસ?','ડેશ બને.'],['કેસ?','lower.'],['ફ્રી?','હા.']]],
    ['slug'=>'string-escape','cat'=>'devtools','name_gu'=>'સ્ટ્રિંગ એસ્કેપ','name_en'=>'String Escaper','icon'=>'quote','premium'=>0,'engine'=>'string-escape',
      'desc_gu'=>'JSON/JS/SQL/HTML માટે સ્ટ્રિંગ escape કરો.','desc_en'=>'Escape strings for JSON, JS, SQL or HTML.',
      'guide'=>$g('ટેક્સ્ટ પેસ્ટ','ટાર્ગેટ પસંદ','escape','કોપી'),
      'faq'=>[['unescape?','હા.'],['SQL?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'chmod-calculator','cat'=>'devtools','name_gu'=>'Chmod કેલ્ક્યુલેટર','name_en'=>'Chmod Calculator','icon'=>'lock','premium'=>0,'engine'=>'chmod-calc',
      'desc_gu'=>'Linux ફાઇલ પરમિશન (755, 644) ગણો.','desc_en'=>'Calculate Linux file permissions (755, 644).',
      'guide'=>$g('પરમિશન ટિક કરો','ઓક્ટલ જુઓ','કમાન્ડ કોપી','વાપરો'),
      'faq'=>[['755?','rwxr-xr-x.'],['કમાન્ડ?','chmod બતાવે.'],['ફ્રી?','હા.']]],
    ['slug'=>'color-converter','cat'=>'devtools','name_gu'=>'કલર કન્વર્ટર','name_en'=>'Color Converter','icon'=>'palette','premium'=>0,'engine'=>'color-convert',
      'desc_gu'=>'HEX, RGB, HSL વચ્ચે કલર કન્વર્ટ કરો.','desc_en'=>'Convert colors between HEX, RGB and HSL.',
      'guide'=>$g('કલર આપો','ફોર્મેટ જુઓ','પિકર વાપરો','કોપી'),
      'faq'=>[['HSL?','હા.'],['પિકર?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'base-converter','cat'=>'devtools','name_gu'=>'બેઝ કન્વર્ટર','name_en'=>'Number Base Converter','icon'=>'binary','premium'=>0,'engine'=>'base-convert',
      'desc_gu'=>'બાઇનરી, ઓક્ટલ, ડેસિમલ, હેક્સ કન્વર્ટ કરો.','desc_en'=>'Convert binary, octal, decimal and hex.',
      'guide'=>$g('મૂલ્ય આપો','બેઝ પસંદ','કન્વર્ટ','કોપી'),
      'faq'=>[['હેક્સ?','હા.'],['કોઈપણ બેઝ?','2-36.'],['ફ્રી?','હા.']]],
    ['slug'=>'meta-tag-generator','cat'=>'devtools','name_gu'=>'મેટા ટેગ જનરેટર','name_en'=>'Meta Tag Generator','icon'=>'tags','premium'=>0,'engine'=>'meta-gen',
      'desc_gu'=>'SEO title, description, OG મેટા ટેગ બનાવો.','desc_en'=>'Generate SEO title, description and OG meta tags.',
      'guide'=>$g('વિગત ભરો','જનરેટ','કોડ કોપી','પેસ્ટ'),
      'faq'=>[['OG?','હા.'],['Twitter?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'robots-txt-generator','cat'=>'devtools','name_gu'=>'Robots.txt જનરેટર','name_en'=>'Robots.txt Generator','icon'=>'bot','premium'=>0,'engine'=>'robots-gen',
      'desc_gu'=>'robots.txt ફાઇલ સરળતાથી બનાવો.','desc_en'=>'Build a robots.txt file easily.',
      'guide'=>$g('નિયમ પસંદ','sitemap ઉમેરો','જનરેટ','ડાઉનલોડ'),
      'faq'=>[['Disallow?','હા.'],['sitemap?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'htaccess-redirect','cat'=>'devtools','name_gu'=>'.htaccess રિડાયરેક્ટ','name_en'=>'.htaccess Redirect Generator','icon'=>'shuffle','premium'=>0,'engine'=>'htaccess-gen',
      'desc_gu'=>'301/302 રિડાયરેક્ટ નિયમ બનાવો.','desc_en'=>'Generate 301/302 redirect rules.',
      'guide'=>$g('જૂનું/નવું URL','પ્રકાર પસંદ','જનરેટ','કોપી'),
      'faq'=>[['301?','હા.'],['www?','હા.'],['ફ્રી?','હા.']]],
    ['slug'=>'text-to-binary','cat'=>'devtools','name_gu'=>'ટેક્સ્ટ ↔ બાઇનરી','name_en'=>'Text to Binary/ASCII','icon'=>'binary','premium'=>0,'engine'=>'text-binary',
      'desc_gu'=>'ટેક્સ્ટને બાઇનરી, ASCII, hex માં કન્વર્ટ કરો.','desc_en'=>'Convert text to binary, ASCII or hex.',
      'guide'=>$g('ટેક્સ્ટ પેસ્ટ','ફોર્મેટ પસંદ','કન્વર્ટ','કોપી'),
      'faq'=>[['ડીકોડ?','હા.'],['hex?','હા.'],['ફ્રી?','હા.']]],
    ];
}

/** Return a single tool definition by slug, or null. */
function kt_tool(string $slug): ?array {
    foreach (kt_tools() as $t) {
        if ($t['slug'] === $slug) return $t;
    }
    return null;
}

/** Return all tools within a category slug. */
function kt_tools_by_cat(string $catSlug): array {
    return array_values(array_filter(kt_tools(), fn($t) => $t['cat'] === $catSlug));
}

/** Return up to $n related tools from the same category (excluding self). */
function kt_related(string $slug, int $n = 4): array {
    $tool = kt_tool($slug);
    if (!$tool) return [];
    $siblings = array_filter(kt_tools_by_cat($tool['cat']), fn($t) => $t['slug'] !== $slug);
    return array_slice(array_values($siblings), 0, $n);
}
